/* SPDX-License-Identifier: GPL-3.0-only */
/* Bryo: the whole app as one translation unit (a unity build: tools/build.py compiles this file). The hardware
 * layer, update path, USB, storage, display and input sit under the instrument (the four tracks, their devices,
 * the UI). Build flags keep their FELUCCA_* names (NOTICE.md says
 * why). Order: config, HAL, generated tables, base and display, the Bryo core, sound, I/O, UI, stores, main. */

#ifndef FELUCCA_FLASH
#define FELUCCA_FLASH 1          /* flash driver + storage.c: settings, projects, user presets */
#endif
#ifndef FELUCCA_OTA
#define FELUCCA_OTA 1            /* M-UPGRADE update entry and the editor SysEx; needs FELUCCA_FLASH */
#endif
#ifndef FELUCCA_OTA_DRYRUN
#define FELUCCA_OTA_DRYRUN 0     /* 1 = stage, ask "success", then undo: no record, no reset */
#endif
#ifndef FELUCCA_CDC
#define FELUCCA_CDC 1            /* USB CDC-ACM serial console */
#endif
#ifndef FELUCCA_UAC
#define FELUCCA_UAC 1            /* USB audio input: the master output, 16-bit stereo 44.1 kHz (usb.c) */
#endif
#ifndef FELUCCA_UAC_TONE
#define FELUCCA_UAC_TONE 0       /* bench: the USB input sends test triangles instead of the music */
#endif
#ifndef FELUCCA_UART
#define FELUCCA_UART 1           /* TRS MIDI IN on UART1 / PH8 */
#endif
#ifndef FELUCCA_ID
#define FELUCCA_ID "FM-1_900"    /* package identity (build.py: the .fwsc marker string) */
#endif
#ifndef FELUCCA_VERSION
#define FELUCCA_VERSION "v0.1.0" /* Bryo's version (based on Felucca 1.0.3): shown in the menu, the console and the
                                  * editor; build.py --release X.Y */
#endif
#if FELUCCA_OTA && !FELUCCA_FLASH
#error "FELUCCA_OTA needs FELUCCA_FLASH"
#endif

/* ------------------------------------------------------------- HAL --- */
#include <stdint.h>
#include "fm1_time.h"
#include "fm1_sys.h"
#include "fm1_irq.h"
#include "fm1_guard.h"
#include "fm1_input.h"
#include "fm1_timer.h"
#include "fm1_audio.h"
#include "fm1_adc.h"
#include "fm1_lcd_hw.h"
#include "felucca_tables.h"      /* generated by build.py (tools/gen_tables.py) */

/* ----------------------------------------------------- base, display --- */
#include "libc.c"
#include "lcd.c"
#include "gfx.c"

/* ------------------------------------------------------- Bryo core --- */
#include "bryo.h"
static void ui_message(const char *s);   /* ui.c: used by panel.c's calibration */
static void ui_redraw(void);

/* ----------------------------------------------------------- sound --- */
#include "dsp.c"                 /* fixed-point helpers */
#include "master.c"              /* the output stage: DC block, speaker EQ, limiter, USB level */
#include "param.c"               /* the parameter table: devices and modulator slots per track */
#include "tape.c"                /* TAPE: the ADPCM looper, the factory reels */
#include "chain.c"               /* the four tracks, rendered per control block */

/* ------------------------------------------------------------- I/O --- */
#include "usb.c"
#if FELUCCA_UART
#include "midi_uart.c"
#endif
#include "audio.c"

/* -------------------------------------------------------------- UI --- */
#include "icons.c"
#include "panel.c"               /* the panel map, the settings in RAM, HARDWARE CALIBRATION */

/* ---------------------------------------------------------- stores --- */
#if FELUCCA_FLASH
#include "fm1_flash.h"
#include "storage_hw.c"
#include "storage.c"
#endif
#include "settings.c"            /* the settings record (shared with Felucca installs: settings.c) */

#include "ui_px.c"              /* the dot grid: bitmap type, strokes, the pictograms */
#include "ui.c"
#include "ui_viz.c"              /* the visualization panel */
#include "ui_input.c"
#if FELUCCA_OTA
#include "ota.c"
#include "ota_hw.c"
#endif
#if FELUCCA_CDC
#include "console.c"
#endif
#include "main.c"
