/* SPDX-License-Identifier: GPL-3.0-only */
/* Bryo: TAPE, each track's looper (docs/bryo-architecture.md, "The tape format, and why", "Memory by usage").
 *
 * Format: IMA ADPCM, 4 bits, mono, 22,050 Hz, low nibble first, in blocks of 256 samples (128 bytes). Each block
 * keeps the decoder state at its start, so any block decodes on its own, and its peak, which the screen draws. The
 * factory reels (tools/gen_reels.py) are the same format in flash.
 *
 * A track's RAM tape is a list of chunks from the shared pool (mem.c), 16 blocks each, as long as what's on it: a
 * reel copied in takes the chunks it needs, a blank tape grows while REC records it. Nothing is reserved per track,
 * so a track that never records holds nothing.
 *
 * What a track plays: its RAM tape, or a reel (TAPE 3's REEL). A reel plays straight from flash; recording on it
 * copies it into the RAM tape first (main loop, tape_prepare), and REEL turns to TAPE. Choosing a reel never
 * touches the RAM tape, so browsing reels loses nothing.
 *
 * Recording a blank tape (REC on a cleared or unused tape): the head starts at the loop's start when the transport
 * plays and runs forward, and the tape grows behind it, a chunk at a time, into chunks the main loop keeps ready
 * (tape_poll). Letting go of REC ends it there: that's the loop's length. When nothing is free the main loop takes
 * chunks (tape_steal): first from cleared tapes, then from tracks switched off (TRACKS), then from the end of the
 * longest tape; when there's nothing left to take, the tape stops growing and loops what it has.
 *
 * Reading (audio ISR): a reader decodes one block into a cache (256 samples plus the next block's first, for the
 * interpolation), so any position in it is a lookup: speed, reverse, slices and grains cost one block decode per
 * 256 samples. Two readers per track: the head, and the old head while a jump (the loop's seam, a slice) fades out.
 *
 * Writing (audio ISR, REC): the writer decodes the block under the head into a staging buffer, mixes each sample
 * (old x its share + input x its share x GAIN: DUB's balance, tape_dub), and when the head leaves the block encodes
 * the whole block back, from a decoder state fitted to its new first sample (stored in the block). Blocks after it
 * keep their own states, so nothing else changes; a reader re-decodes a block after it is committed, so it sees the
 * old block or the new one, never a mix. A block whose chunk has been taken away meanwhile is dropped.
 *
 * Clearing (the POLY key, held) marks the tape empty and keeps its chunks, so SAVE held can undo it until the next
 * recording writes over it or the chunks are taken.
 *
 * Ownership: the main loop owns tape_ctl[]'s chunk list (it publishes nch after the list entries) and the RAM tape
 * outside recording; the ISR owns tape_rt[] and, while recording, the RAM tape, and while a blank tape grows, its
 * length (nblk) and the end of the growth (grow). Integer only, no 64-bit maths. */

#include "bryo_reels.h"              /* generated by tools/gen_reels.py */

#define TAPE_BLK 256u                /* samples per block */
#define TAPE_NBLK 288u               /* the longest factory reel, and a one-slot user reel: 3.34 s */
#define TAPE_LEN (TAPE_BLK * TAPE_NBLK)
#define TAPE_CHS (MEM_CB * TAPE_BLK)                    /* samples a chunk holds */
#define TAPE_MAXCH 127u              /* a tape's most chunks: 23.6 s. The head is in Q12 samples in an int32, which
                                      * holds 524,288 samples (23.8 s); 127 chunks leave room for a step past the end */
#define TAPE_SR 22050
#define TAPE_DECLICK 88              /* the shortest fade (a jump, start and stop): 2 ms at 44.1 kHz */

/* the knobs (param.c DEV_P[DEV_SRC]) */
enum { TK_STRT, TK_LEN, TK_SPD, TK_DUB, TK_FADE, TK_REV, TK_HALF, TK_GAIN, TK_REEL, TK_ROTA };

typedef struct {                     /* a reel in flash (bryo_reels.h REELS_INIT) */
    const char *name;
    uint16_t nblk;
    const uint8_t *data;
    const int16_t *pred;
    const uint8_t *idx;
    const uint8_t *peak;
} reel_t;
static const reel_t REELS[NREEL] = {REELS_INIT};

typedef struct {                     /* main loop writes the list, ISR reads it once per block */
    volatile uint8_t empty;          /* the RAM tape is cleared (its chunks kept for undo until REC or a steal) */
    volatile uint8_t rec_ok;         /* the RAM tape is ready for REC (tape_prepare) */
    volatile uint8_t grow;           /* a blank tape being recorded: it grows behind the head (the ISR ends it) */
    volatile uint8_t nch;            /* chunks in the list */
    volatile uint16_t nblk;          /* the RAM tape's length in blocks (0: never used); the ISR's while growing */
    volatile uint8_t gen;            /* bumped when the list is let go or replaced: a block staged before is dropped */
    uint8_t map[MEM_NC];             /* the chunks, in order */
} tape_ctl_t;
static tape_ctl_t tape_ctl[NTRK];
static volatile uint32_t tape_ver[NTRK];  /* bumped when what a track plays changes (a commit, a clear): the screen redraws */

typedef struct {                     /* what a track plays now */
    const uint8_t *data;             /* in flash: blocks end to end, their states and peaks in arrays */
    const int16_t *pred;
    const uint8_t *idx;
    const uint8_t *peak;
    uint32_t len;                    /* samples; 0: silence */
    uint8_t ram;                     /* the RAM tape (it can be written) */
    const uint8_t *map;              /* in RAM: the chunk list instead (0: flash) */
} tape_view_t;

/* block b of a view: its data, decoder state and peak, from flash's arrays or the chunk that holds it */
static inline const mem_chunk_t *tv_chunk(const tape_view_t *v, uint32_t b) { return mem_at(v->map[b / MEM_CB]); }
static inline const uint8_t *tv_data(const tape_view_t *v, uint32_t b)
{
    return v->map ? tv_chunk(v, b)->data[b % MEM_CB] : v->data + b * (TAPE_BLK / 2u);
}
static inline int32_t tv_pred(const tape_view_t *v, uint32_t b) { return v->map ? tv_chunk(v, b)->pred[b % MEM_CB] : v->pred[b]; }
static inline int32_t tv_idx(const tape_view_t *v, uint32_t b) { return v->map ? tv_chunk(v, b)->idx[b % MEM_CB] : v->idx[b]; }
static inline uint32_t tv_peak(const tape_view_t *v, uint32_t b) { return v->map ? tv_chunk(v, b)->peak[b % MEM_CB] : v->peak[b]; }

/* block b of track t's RAM tape, to write */
static inline mem_chunk_t *tape_chunk(uint32_t t, uint32_t b) { return mem_at(tape_ctl[t].map[b / MEM_CB]); }

typedef struct {                     /* a decoded block */
    int16_t s[TAPE_BLK + 1u];        /* + the next block's first sample */
    uint16_t blk;
    uint8_t ok;
} tape_rd_t;

typedef struct {                     /* ISR only */
    tape_rd_t a, b;                  /* the head's block; the old head's while a jump fades */
    int16_t stage[TAPE_BLK];         /* the writer's block, decoded and being mixed */
    int32_t pos;                     /* the head, in samples Q12 (22.05 kHz units) */
    int32_t xpos;                    /* the old head during a fade */
    int32_t xf, xflen;               /* the fade: output samples left, its length */
    int32_t stop_left;               /* a slice played while stopped: the head's travel left (Q12), 0: no end */
    int32_t amp;                     /* start/stop ramp, Q15 */
    int32_t wlast;                   /* the last sample written, -1: none */
    uint16_t wblk;                   /* the staged block */
    uint8_t wstaged;                 /* stage holds wblk */
    uint8_t running;                 /* the head moves */
    uint8_t was_playing;
    uint8_t grew;                    /* the head has started on a growing tape */
    uint8_t wgen;                    /* the list's gen when the staged block was read */
    uint32_t keys_prev;
} tape_rt_t;
static tape_rt_t tape_rt[NTRK] __attribute__((section(".pool")));

/* the clear's undo: one, for the last clear, until REC writes over it */
static struct {
    uint8_t valid, trk, src, empty;
} tape_undo;

/* a gain in dB (-24..24) as Q10: 2x per 6 dB, straight between */
static int32_t db_q10(int32_t db)
{
    int32_t f = 1024;
    for (; db >= 6; db -= 6)
        f *= 2;
    for (; db <= -6; db += 6)
        f /= 2;
    return db >= 0 ? f + f * db / 6 : f - f * (-db) / 12;
}

/* ------------------------------------------------------------- codec --- */
static const int16_t IMA_STEP[89] = {
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31, 34, 37, 41, 45, 50, 55, 60, 66, 73, 80, 88, 97,
    107, 118, 130, 143, 157, 173, 190, 209, 230, 253, 279, 307, 337, 371, 408, 449, 494, 544, 598, 658, 724, 796,
    876, 963, 1060, 1166, 1282, 1411, 1552, 1707, 1878, 2066, 2272, 2499, 2749, 3024, 3327, 3660, 4026, 4428, 4871,
    5358, 5894, 6484, 7132, 7845, 8630, 9493, 10442, 11487, 12635, 13899, 15289, 16818, 18500, 20350, 22385, 24623,
    27086, 29794, 32767};
static const int8_t IMA_IDX[8] = {-1, -1, -1, -1, 2, 4, 6, 8};

/* one nibble into the decoder state */
static inline int32_t ima_step(int32_t *pred, int32_t *idx, uint32_t code)
{
    int32_t step = IMA_STEP[*idx], vd = step >> 3, p;
    if (code & 4u)
        vd += step;
    if (code & 2u)
        vd += step >> 1;
    if (code & 1u)
        vd += step >> 2;
    p = (code & 8u) ? *pred - vd : *pred + vd;
    *pred = clamp(p, -32768, 32767);
    *idx = clamp(*idx + IMA_IDX[code & 7u], 0, 88);
    return *pred;
}

/* n samples of a block (from its stored state) into out */
static void ima_dec(const uint8_t *data, int32_t pred, int32_t idx, int16_t *out, uint32_t n)
{
    uint32_t i;
    for (i = 0; i < n; i++)
        out[i] = (int16_t)ima_step(&pred, &idx, (data[i >> 1] >> ((i & 1u) * 4u)) & 15u);
}

/* n samples into a block, from the state (*pred, *idx), which is left at the block's end: the encoder
 * tools/gen_reels.py runs */
static void ima_enc_st(const int16_t *in, int32_t *pst, int32_t *ist, uint8_t *data, uint32_t n)
{
    int32_t pred = *pst, idx = *ist;
    uint32_t i;
    for (i = 0; i < n; i++) {
        int32_t step = IMA_STEP[idx], diff = in[i] - pred, code = 0;
        if (diff < 0) {
            code = 8;
            diff = -diff;
        }
        if (diff >= step) {
            code |= 4;
            diff -= step;
        }
        if (diff >= step >> 1) {
            code |= 2;
            diff -= step >> 1;
        }
        if (diff >= step >> 2)
            code |= 1;
        ima_step(&pred, &idx, (uint32_t)code);
        if (i & 1u)
            data[i >> 1] = (uint8_t)((data[i >> 1] & 15u) | ((uint32_t)code << 4));
        else
            data[i >> 1] = (uint8_t)code;
    }
    *pst = pred;
    *ist = idx;
}

static void ima_enc(const int16_t *in, int32_t pred, int32_t idx, uint8_t *data, uint32_t n)
{
    ima_enc_st(in, &pred, &idx, data, n);
}

/* -------------------------------------------------------------- views --- */
static int uslot_view(uint32_t s, tape_view_t *v);   /* reel.c: a user reel in flash */

/* what a track has chosen: 0 its RAM tape, 1..NREEL a factory reel, then the user reels */
static uint32_t tape_src(uint32_t t) { return (uint32_t)clamp(tp[t].dev[DEV_SRC][TK_REEL], 0, (int32_t)(NREEL + USLOT_N)); }

/* what reel choice s (0: track t's RAM tape, 1..NREEL a factory reel, then the user reels) holds; POLY reads any of
 * them this way, whatever the track's TAPE plays */
static void tape_view_of(uint32_t t, uint32_t s, tape_view_t *v)
{
    v->map = 0;
    if (s > NREEL) {                                   /* a user reel (an empty slot plays nothing) */
        if (!uslot_view(s - NREEL - 1u, v)) {
            v->len = 0;
            v->ram = 0;
            v->data = 0;                               /* (never read: len 0) */
            v->pred = 0;
            v->idx = 0;
            v->peak = 0;
        }
        return;
    }
    if (s) {
        const reel_t *r = &REELS[s - 1u];
        v->data = r->data;
        v->pred = r->pred;
        v->idx = r->idx;
        v->peak = r->peak;
        v->len = r->nblk * TAPE_BLK;
        v->ram = 0;
        return;
    }
    v->data = 0;
    v->pred = 0;
    v->idx = 0;
    v->peak = 0;
    v->map = tape_ctl[t].map;
    v->len = tape_ctl[t].empty ? 0u : tape_ctl[t].nblk * TAPE_BLK;
    if (v->len > (uint32_t)tape_ctl[t].nch * TAPE_CHS)   /* (a tape its chunks were taken from: what's left) */
        v->len = (uint32_t)tape_ctl[t].nch * TAPE_CHS;
    v->ram = 1;
}

static void tape_view(uint32_t t, tape_view_t *v) { tape_view_of(t, tape_src(t), v); }

/* the loop window in samples: STRT and LEN in % of what the track plays (at least one block long) */
static void tape_window(uint32_t t, uint32_t len, int32_t *ls, int32_t *ll)
{
    const int16_t *k = tp[t].dev[DEV_SRC];
    int32_t s = (int32_t)len * k[TK_STRT] / 100, l = (int32_t)len * k[TK_LEN] / 100;
    if (l < (int32_t)TAPE_BLK)
        l = (int32_t)TAPE_BLK;
    if (s + l > (int32_t)len)
        s = (int32_t)len - l;
    *ls = s < 0 ? 0 : s;
    *ll = l > (int32_t)len ? (int32_t)len : l;
}

/* the head's step per output sample, Q12 of a tape sample: 0.5 at 100 % (22.05 kHz under 44.1 kHz); SPD
 * -200..200 %, REV turns it round, HALF halves it */
static int32_t tape_inc(uint32_t t)
{
    const int16_t *k = tp[t].dev[DEV_SRC];
    int32_t inc = 2048 * k[TK_SPD] / 100;
    if (k[TK_REV])
        inc = -inc;
    return k[TK_HALF] ? inc / 2 : inc;
}

/* sample i of the view through reader r (silence outside it) */
static int32_t tape_at(const tape_view_t *v, tape_rd_t *r, int32_t i)
{
    uint32_t blk, o;
    if (i < 0 || (uint32_t)i >= v->len)
        return 0;
    blk = (uint32_t)i / TAPE_BLK;
    o = (uint32_t)i % TAPE_BLK;
    if (!r->ok || r->blk != blk) {
        ima_dec(tv_data(v, blk), tv_pred(v, blk), tv_idx(v, blk), r->s, TAPE_BLK);
        if ((blk + 1u) * TAPE_BLK < v->len) {          /* the next block's first sample */
            int32_t p = tv_pred(v, blk + 1u), x = tv_idx(v, blk + 1u);
            r->s[TAPE_BLK] = (int16_t)ima_step(&p, &x, tv_data(v, blk + 1u)[0] & 15u);
        } else {
            r->s[TAPE_BLK] = r->s[TAPE_BLK - 1u];
        }
        r->blk = (uint16_t)blk;
        r->ok = 1;
    }
    return r->s[o];
}

/* the view at head position pos (Q12), interpolated */
static int32_t tape_read(const tape_view_t *v, tape_rd_t *r, int32_t pos)
{
    int32_t i = pos >> 12, f = pos & 4095, a = tape_at(v, r, i), b;
    if (i < 0 || (uint32_t)i >= v->len)
        return 0;
    b = r->s[((uint32_t)i % TAPE_BLK) + 1u];
    return a + (((b - a) * f) >> 12);
}

/* ------------------------------------------------------------- writer --- */
/* a block's decoder state fitted to its sound: its first sample and the step that suits its first move (an encoder
 * that starts from some other block's state takes a while to catch up: a click a block) */
static void ima_fit(const int16_t *s, int16_t *pred, uint8_t *idx)
{
    int32_t d = s[1] - s[0], id = 0;
    d = d < 0 ? -d : d;
    while (id < 88 && IMA_STEP[id] < d)
        id++;
    *pred = s[0];
    *idx = (uint8_t)id;
}

/* a block's peak, as the screen keeps it */
static uint8_t ima_peak(const int16_t *s, uint32_t n)
{
    uint32_t i;
    int32_t pk = 0;
    for (i = 0; i < n; i++) {
        int32_t a = s[i] < 0 ? -s[i] : s[i];
        if (a > pk)
            pk = a;
    }
    return (uint8_t)(pk >> 7 > 255 ? 255 : pk >> 7);
}

static void tape_commit(uint32_t t)
{
    tape_rt_t *rt = &tape_rt[t];
    uint32_t b = rt->wblk;
    mem_chunk_t *c;
    if (!rt->wstaged)
        return;
    rt->wstaged = 0;
    if (tape_ctl[t].empty || b / MEM_CB >= tape_ctl[t].nch || rt->wgen != tape_ctl[t].gen)
        return;                                        /* cleared meanwhile, its chunk taken, another tape: drop it */
    c = tape_chunk(t, b);
    ima_fit(rt->stage, &c->pred[b % MEM_CB], &c->idx[b % MEM_CB]);
    ima_enc(rt->stage, c->pred[b % MEM_CB], c->idx[b % MEM_CB], c->data[b % MEM_CB], TAPE_BLK);
    c->peak[b % MEM_CB] = ima_peak(rt->stage, TAPE_BLK);
    tape_ver[t]++;
    if (rt->a.blk == b)                                /* readers decode the new block from now on */
        rt->a.ok = 0;
    if (rt->b.blk == b)
        rt->b.ok = 0;
}

/* sample i of the RAM tape becomes old x keep % + in (in: already scaled by its share) */
/* DUB (-100..100) as the old sound's and the new sound's shares, in %: the S-4's SOS, a Morphagene's SOS. 0 is
 * sound on sound (both whole); toward +100 the input fades and the loop stays (+100: REC changes nothing); toward
 * -100 the loop fades on each pass under the input (-100: the input replaces it) */
static void tape_dub(int32_t dub, int32_t *keep, int32_t *in)
{
    *keep = dub >= 0 ? 100 : 100 + dub;
    *in = dub <= 0 ? 100 : 100 - dub;
}

static void tape_write(uint32_t t, int32_t i, int32_t in, int32_t keep)
{
    tape_rt_t *rt = &tape_rt[t];
    uint32_t b = (uint32_t)i / TAPE_BLK;
    if (!rt->wstaged || rt->wblk != b) {
        mem_chunk_t *c = tape_chunk(t, b);
        tape_commit(t);
        ima_dec(c->data[b % MEM_CB], c->pred[b % MEM_CB], c->idx[b % MEM_CB], rt->stage, TAPE_BLK);
        rt->wblk = (uint16_t)b;
        rt->wgen = tape_ctl[t].gen;
        rt->wstaged = 1;
    }
    rt->stage[(uint32_t)i % TAPE_BLK] = (int16_t)clamp(rt->stage[(uint32_t)i % TAPE_BLK] * keep / 100 + in, -32767, 32767);
}

/* ------------------------------------------------------------ the head --- */
/* jump the head to pos, the old head fading out over the fade (FADE, or at least TAPE_DECLICK) */
static void tape_jump(uint32_t t, int32_t pos)
{
    tape_rt_t *rt = &tape_rt[t];
    int32_t fl = tp[t].dev[DEV_SRC][TK_FADE] * 441 / 10;   /* ms -> output samples */
    rt->xpos = rt->pos;
    rt->b.ok = 0;
    rt->xflen = rt->xf = fl > TAPE_DECLICK ? fl : TAPE_DECLICK;
    rt->pos = pos;
}

/* where in the loop window [ls, ls + ll) the head sits at its offset o from ROTATE's start (wrapped) */
static int32_t tape_rot(uint32_t t, int32_t ls, int32_t ll, int32_t o)
{
    int32_t r = (ll * tp[t].dev[DEV_SRC][TK_ROTA] / 100 + o) % ll;
    return ls + (r < 0 ? r + ll : r);
}

/* white key k: play from slice k of the loop (16 slices); stopped, play just that slice (backwards from its end
 * when the tape runs in reverse) */
static void tape_slice(uint32_t t, uint32_t k, int32_t ls, int32_t ll, int32_t inc)
{
    tape_rt_t *rt = &tape_rt[t];
    int32_t o0 = ll * (int32_t)k / 16, o1 = ll * ((int32_t)k + 1) / 16;   /* (counted from ROTATE's start) */
    tape_jump(t, (inc < 0 ? tape_rot(t, ls, ll, o1 - 1) : tape_rot(t, ls, ll, o0)) << 12);
    if (!sys.playing) {
        rt->running = 1;
        rt->stop_left = (o1 - o0) << 12;              /* (a slice may run over the seam: its length, not its end) */
    }
}

/* audio ISR: n output samples of track t (mono Q15, before level) into out; keys: the white keys held on this
 * track; rec_in: what REC records (n samples), 0 when not recording */
static void tape_block(uint32_t t, uint32_t keys, const int32_t *rec_in, int32_t *out, uint32_t n)
{
    tape_rt_t *rt = &tape_rt[t];
    tape_ctl_t *c = &tape_ctl[t];
    tape_view_t v;
    int32_t ls, ll, inc = tape_inc(t), i, keep, inl, gain = db_q10(tp[t].dev[DEV_SRC][TK_GAIN]), wlen;
    uint32_t k, press = keys & ~rt->keys_prev, playing = sys.playing;
    int rec = rec_in && c->rec_ok && tape_src(t) == 0u, grow;
    if (c->grow && !rec) {                             /* REC let go of a growing tape: its length is what it has */
        c->grow = 0;
        rt->grew = 0;
    }
    grow = c->grow;
    tape_view(t, &v);
    if (grow) {                                        /* growing: forward from the start, no seam until it's full */
        wlen = (int32_t)c->nch * (int32_t)TAPE_CHS;
        ls = 0;
        ll = wlen;
        inc = inc < 0 ? -inc : inc;
        if (!rt->grew && playing) {
            rt->grew = 1;
            rt->pos = 0;
            rt->xf = 0;
            rt->wlast = -1;
            rt->running = 1;
            rt->stop_left = 0;
            rt->was_playing = 1;
        }
    } else {
        wlen = (int32_t)v.len;
        tape_window(t, v.len ? v.len : TAPE_LEN, &ls, &ll);
        if (v.len && rt->running && ((rt->pos >> 12) < ls || (rt->pos >> 12) >= ls + ll)) {
            int32_t o = ((rt->pos >> 12) - ls) % ll;  /* (the tape got shorter under the head: back inside) */
            tape_jump(t, (ls + (o < 0 ? o + ll : o)) << 12);
            rt->wlast = -1;
        }
    }
    rt->keys_prev = keys;
    tape_dub(grow ? -100 : tp[t].dev[DEV_SRC][TK_DUB], &keep, &inl);   /* (a blank tape: nothing to keep) */
    gain = gain * inl / 100;
    if (!inl)
        rec = 0;                                       /* DUB +100: nothing comes in, so nothing is re-encoded */
    if (playing != rt->was_playing) {                  /* the transport: all heads from the loop's start (ROTATE's) */
        rt->was_playing = (uint8_t)playing;
        if (playing) {
            rt->pos = (grow ? 0 : tape_rot(t, ls, ll, inc < 0 ? -1 : 0)) << 12;
            rt->xf = 0;
            rt->running = 1;
            rt->stop_left = 0;
        } else {
            rt->running = 0;                           /* (the ramp fades it) */
        }
    }
    for (k = 0; press && !grow && k < NWHITE; k++)       /* a new key: its slice (the lowest, one per block) */
        if ((press >> k) & 1u) {
            tape_slice(t, k, ls, ll, inc);
            break;
        }
    if (!rec && rt->wstaged)
        tape_commit(t);                                /* REC let go: the last block */
    for (i = 0; i < (int32_t)n; i++) {
        int32_t s = 0, tgt = rt->running ? 32767 : 0;
        rt->amp += rt->amp < tgt ? 372 : rt->amp > tgt ? -372 : 0;   /* ~2 ms either way */
        rt->amp = clamp(rt->amp, 0, 32767);
        if (rt->amp) {
            s = tape_read(&v, &rt->a, rt->pos);
            if (rt->xf > 0) {                          /* the old head fading out */
                int32_t o = tape_read(&v, &rt->b, rt->xpos);
                s = (s * (rt->xflen - rt->xf) + o * rt->xf) / rt->xflen;
                rt->xpos += inc;
                rt->xf--;
            }
            s = (s * rt->amp) >> 15;
        }
        out[i] = s;
        if (!rt->running)
            continue;
        if (rec && playing) {                          /* REC: every tape sample the head passes */
            int32_t a = rt->pos >> 12, w = rt->wlast < 0 ? a : rt->wlast, in = rec_in[i] * gain >> 10;
            if (w != a) {
                int32_t d = a > w ? 1 : -1;
                for (w += d; w != a + d; w += d)
                    if (w >= 0 && w < wlen)
                        tape_write(t, w, in, keep);
            } else if (rt->wlast < 0 && a >= 0 && a < wlen) {
                tape_write(t, a, in, keep);
            }
            rt->wlast = a;
            if (grow && a >= 0 && a < wlen && (uint32_t)a / TAPE_BLK >= c->nblk)
                c->nblk = (uint16_t)((uint32_t)a / TAPE_BLK + 1u);   /* the tape is as long as the head has gone */
        } else {
            rt->wlast = -1;
        }
        rt->pos += inc;
        if (rt->stop_left > 0 && (rt->stop_left -= inc < 0 ? -inc : inc) <= 0) {
            rt->running = 0;                           /* a slice played while stopped: its end */
            rt->stop_left = 0;
        } else if (inc >= 0 && rt->pos >= (ls + ll) << 12) {
            if (grow) {                                /* every chunk filled: it stops growing and loops */
                c->grow = 0;
                rt->grew = 0;
                grow = 0;
                c->nblk = (uint16_t)((uint32_t)wlen / TAPE_BLK);
            }
            tape_jump(t, rt->pos - (ll << 12));        /* the seam, crossfaded */
            rt->wlast = -1;
        } else if (inc < 0 && rt->pos < ls << 12) {
            tape_jump(t, rt->pos + (ll << 12));
            rt->wlast = -1;
        }
    }
}

/* ----------------------------------------------------- main loop side --- */
static void tape_init(void)
{
    uint32_t t;
    mem_init();
    for (t = 0; t < NTRK; t++) {
        tape_rt[t].wlast = -1;
        tape_rt[t].stop_left = 0;
        tape_ctl[t].nblk = 0;
        tape_ctl[t].nch = 0;
        tape_ctl[t].grow = 0;
        tape_ctl[t].empty = 0;
    }
}

/* track t's tape gives up its last chunk (the list shortened first, then the chunk freed: mem.c) */
static void tape_drop_chunk(uint32_t t)
{
    tape_ctl_t *c = &tape_ctl[t];
    uint32_t n = c->nch;
    if (!n)
        return;
    if (c->nblk > (n - 1u) * MEM_CB)
        c->nblk = (uint16_t)((n - 1u) * MEM_CB);
    c->nch = (uint8_t)(n - 1u);
    mem_free(c->map[n - 1u]);
    if (tape_undo.valid && tape_undo.trk == t)       /* (a cleared take that lost a chunk can't come back) */
        tape_undo.valid = 0;
    tape_ver[t]++;
}

/* every chunk of track t's tape back to the pool */
static void tape_free(uint32_t t)
{
    tape_ctl[t].gen++;                                 /* (a block the ISR staged on it is dropped, not committed) */
    tape_ctl[t].nblk = 0;
    while (tape_ctl[t].nch)
        tape_drop_chunk(t);
}

/* a parked track: TRACKS is set below it, so it's switched off */
static int tape_parked(uint32_t t) { return sys.ntrk && t >= sys.ntrk; }

/* Nothing free: take a chunk off the end of a tape, in this order, never from track except or a tape that's
 * growing: a cleared tape, a parked track's tape (the longest), then, when `active` allows, the longest tape of all.
 * Returns 1 when a chunk came free. */
static int tape_steal(uint32_t except, int active)
{
    uint32_t t, best = NTRK, bn = 0, pass;
    for (pass = 0; pass < 3u; pass++) {
        if (pass == 2u && !active)
            break;
        for (t = 0; t < NTRK; t++) {
            tape_ctl_t *c = &tape_ctl[t];
            if (t == except || c->grow || !c->nch)
                continue;
            if (pass == 0u && !c->empty)
                continue;
            if (pass == 1u && !tape_parked(t))
                continue;
            if (c->nch > bn) {
                bn = c->nch;
                best = t;
            }
        }
        if (best < NTRK) {
            tape_drop_chunk(best);
            return 1;
        }
    }
    return 0;
}

/* a chunk for owner o (taking one when none is free; active: as tape_steal), or -1 */
static int32_t tape_alloc(uint32_t o, uint32_t except, int active)
{
    int32_t c = mem_alloc(o);
    if (c < 0 && tape_steal(except, active))
        c = mem_alloc(o);
    return c;
}

/* track t's tape holds at least nch chunks (stealing as tape_steal allows); returns how many it holds */
static uint32_t tape_reserve(uint32_t t, uint32_t nch, int active)
{
    tape_ctl_t *c = &tape_ctl[t];
    while (c->nch < nch && c->nch < TAPE_MAXCH) {
        int32_t k = tape_alloc(MEM_TAPE + t, t, active);
        if (k < 0)
            break;
        c->map[c->nch] = (uint8_t)k;
        RING_PUBLISH();                                /* (the entry before the count that hands it to the ISR) */
        c->nch++;
    }
    return c->nch;
}

/* REC armed on track t: make its RAM tape ready to be written. A reel is copied in (REEL turns to TAPE), taking the
 * chunks it needs; a cleared or unused tape starts blank and grows as it records. Returns 1 ready; 0, leaving REC
 * off, when a reel would overwrite a RAM tape that holds a take (clear it, or set REEL to TAPE, first); -1 when
 * there's no memory to record into. */
static int tape_prepare(uint32_t t)
{
    tape_ctl_t *c = &tape_ctl[t];
    uint32_t s = tape_src(t), b, nb;
    if (c->rec_ok)
        return 1;
    if (s) {                                           /* a reel (factory or yours): copied onto the tape */
        tape_view_t v;
        if (c->nblk && !c->empty)
            return 0;
        tape_view(t, &v);
        nb = v.len / TAPE_BLK;
        if (!nb)                                       /* an empty user slot: record onto a blank tape */
            goto blank;
        c->empty = 1;                                  /* (silent while it's copied) */
        tape_free(t);
        if (tape_reserve(t, (nb + MEM_CB - 1u) / MEM_CB, 1) * MEM_CB < nb)
            nb = (uint32_t)c->nch * MEM_CB;            /* (not all of it fits: as much as does) */
        if (!nb)
            return -1;
        for (b = 0; b < nb; b++) {
            mem_chunk_t *m = tape_chunk(t, b);
            memcpy(m->data[b % MEM_CB], tv_data(&v, b), TAPE_BLK / 2u);
            m->pred[b % MEM_CB] = (int16_t)tv_pred(&v, b);
            m->idx[b % MEM_CB] = (uint8_t)tv_idx(&v, b);
            m->peak[b % MEM_CB] = (uint8_t)tv_peak(&v, b);
        }
        c->nblk = (uint16_t)nb;
        c->empty = 0;
        tp[t].dev[DEV_SRC][TK_REEL] = 0;               /* the track plays its tape (the same sound) */
    } else if (c->empty || !c->nblk) {
    blank:
        c->empty = 1;
        tape_free(t);
        if (tape_reserve(t, 2u, 1) == 0u)              /* (two chunks ready: the main loop adds the rest in time) */
            return -1;
        tp[t].dev[DEV_SRC][TK_REEL] = 0;
        c->nblk = 0;
        tape_rt[t].grew = 0;
        c->grow = 1;
        c->empty = 0;
    }
    if (tape_undo.valid && tape_undo.trk == t)         /* the cleared take is gone now */
        tape_undo.valid = 0;
    RING_PUBLISH();
    c->rec_ok = 1;
    tape_ver[t]++;
    return 1;
}

static void tape_unprepare(uint32_t t) { tape_ctl[t].rec_ok = 0; }

/* main loop, every pass: a growing tape keeps a chunk ready ahead of its head; one done growing gives back the chunks
 * past its end */
static void tape_poll(void)
{
    uint32_t t;
    for (t = 0; t < NTRK; t++) {
        tape_ctl_t *c = &tape_ctl[t];
        if (c->grow) {
            if ((uint32_t)c->nch * MEM_CB < c->nblk + 2u * MEM_CB)   /* (two chunks, 372 ms, ready ahead) */
                tape_reserve(t, c->nch + 1u, 1);
        } else if (!c->rec_ok && !c->empty) {
            while (c->nch && (uint32_t)(c->nch - 1u) * MEM_CB >= c->nblk)
                tape_drop_chunk(t);
        }
    }
}

/* the POLY key held: clear what track t plays (a reel: the track goes back to its tape, cleared) */
static void tape_clear(uint32_t t)
{
    tape_ctl[t].rec_ok = 0;
    tape_ctl[t].grow = 0;
    tape_undo.valid = 1;
    tape_undo.trk = (uint8_t)t;
    tape_undo.src = (uint8_t)tape_src(t);
    tape_undo.empty = tape_ctl[t].empty;
    tp[t].dev[DEV_SRC][TK_REEL] = 0;
    tape_ctl[t].empty = 1;
    tape_ver[t]++;
}

/* SAVE held: undo the last clear, while nothing has been recorded over it; returns the track, or -1 */
static int32_t tape_undo_clear(void)
{
    uint32_t t = tape_undo.trk;
    if (!tape_undo.valid)
        return -1;
    tape_undo.valid = 0;
    tape_ctl[t].empty = tape_undo.empty;
    tp[t].dev[DEV_SRC][TK_REEL] = tape_undo.src;
    tape_ver[t]++;
    return (int32_t)t;
}

/* for the screen: the peak (0..1000) of what track t plays at pos (0..1000 of it), and where its head is (0..1000;
 * -1 when it isn't running) */
static int32_t tape_peak_at(uint32_t t, int32_t pos)
{
    tape_view_t v;
    uint32_t b;
    tape_view(t, &v);
    if (!v.len)
        return 0;
    b = (uint32_t)clamp(pos, 0, 999) * (v.len / TAPE_BLK) / 1000u;
    return (int32_t)tv_peak(&v, b) * 1000 / 255;
}

static int32_t tape_head(uint32_t t)
{
    tape_view_t v;
    tape_view(t, &v);
    if (!tape_rt[t].running || !v.len)
        return -1;
    return clamp((tape_rt[t].pos >> 12) * 1000 / (int32_t)v.len, 0, 1000);
}

/* the length of what track t plays, in ms (0: nothing) */
static int32_t tape_ms(uint32_t t)
{
    tape_view_t v;
    tape_view(t, &v);
    return (int32_t)(v.len * 10u / (TAPE_SR / 100u));
}

/* the name of what track t plays: a reel's, TAPE, or EMPTY */
static const char *tape_name_of(uint32_t t, uint32_t s)   /* reel choice s, as the screen names it */
{
    if (s > NREEL)
        return uslot_name[s - NREEL - 1u];
    return s ? REELS[s - 1u].name : tape_ctl[t].empty || !tape_ctl[t].nblk ? "EMPTY" : "TAPE";
}

static const char *tape_name(uint32_t t) { return tape_name_of(t, tape_src(t)); }
