/* SPDX-License-Identifier: GPL-3.0-only */
/* Bryo: TAPE, each track's looper (docs/bryo-architecture.md, "The tape format, and why").
 *
 * Format: IMA ADPCM, 4 bits, mono, 22,050 Hz, low nibble first, in blocks of 256 samples (128 bytes). Each block
 * keeps the decoder state at its start, so any block decodes on its own, and its peak, which the screen draws.
 * A RAM tape is 288 blocks: 73,728 samples, 3.34 s, 36 KiB, in the pool. The factory reels (tools/gen_reels.py)
 * are the same format in flash.
 *
 * What a track plays: its RAM tape, or a reel (TAPE 3's REEL). A reel plays straight from flash; recording on it
 * copies it into the RAM tape first (main loop, tape_prepare), and REEL turns to TAPE. Choosing a reel never
 * touches the RAM tape, so browsing reels loses nothing.
 *
 * Reading (audio ISR): a reader decodes one block into a cache (256 samples plus the next block's first, for the
 * interpolation), so any position in it is a lookup: speed, reverse, slices and grains cost one block decode per
 * 256 samples. Two readers per track: the head, and the old head while a jump (the loop's seam, a slice) fades out.
 *
 * Writing (audio ISR, REC): the writer decodes the block under the head into a staging buffer, mixes each sample
 * (old x DUB + input x GAIN), and when the head leaves the block encodes the whole block back, starting from the
 * block's own stored state. Blocks after it keep their own states, so nothing else changes; a reader re-decodes a
 * block after it is committed, so it sees the old block or the new one, never a mix.
 *
 * Clearing (the POLY key, held) marks the tape empty and keeps its data, so SAVE held can undo it until the next
 * recording writes over it.
 *
 * Ownership: the main loop owns tape_ctl[] (whole bytes the ISR reads once per block) and the RAM tape outside
 * recording; the ISR owns tape_rt[] and, while recording, the RAM tape. Integer only, no 64-bit maths. */

#include "bryo_reels.h"              /* generated by tools/gen_reels.py */

#define TAPE_BLK 256u                /* samples per block */
#define TAPE_NBLK 288u               /* blocks per RAM tape */
#define TAPE_LEN (TAPE_BLK * TAPE_NBLK)                 /* 73,728 samples: 3.34 s at 22.05 kHz */
#define TAPE_SR 22050
#define TAPE_DECLICK 88              /* the shortest fade (a jump, start and stop): 2 ms at 44.1 kHz */

/* the knobs (param.c DEV_P[DEV_SRC]) */
enum { TK_STRT, TK_LEN, TK_SPD, TK_DUB, TK_FADE, TK_REV, TK_HALF, TK_GAIN, TK_REEL };

typedef struct {                     /* a reel in flash (bryo_reels.h REELS_INIT) */
    const char *name;
    uint16_t nblk;
    const uint8_t *data;
    const int16_t *pred;
    const uint8_t *idx;
    const uint8_t *peak;
} reel_t;
static const reel_t REELS[NREEL] = {REELS_INIT};

typedef struct {                     /* a RAM tape */
    uint8_t data[TAPE_LEN / 2u];
    int16_t pred[TAPE_NBLK];
    uint8_t idx[TAPE_NBLK];
    uint8_t peak[TAPE_NBLK];
} tape_ram_t;
static tape_ram_t tape_ram[NTRK] __attribute__((section(".pool")));

typedef struct {                     /* main loop writes, ISR reads */
    volatile uint8_t empty;          /* the RAM tape is cleared (its data kept for undo until REC writes) */
    volatile uint8_t rec_ok;         /* the RAM tape is ready for REC (tape_prepare) */
    volatile uint16_t nblk;          /* the RAM tape's length in blocks (0: never used) */
} tape_ctl_t;
static tape_ctl_t tape_ctl[NTRK];
static volatile uint32_t tape_ver[NTRK];  /* bumped when what a track plays changes (a commit, a clear): the screen redraws */

typedef struct {                     /* what a track plays now */
    const uint8_t *data;
    const int16_t *pred;
    const uint8_t *idx;
    const uint8_t *peak;
    uint32_t len;                    /* samples; 0: silence */
    uint8_t ram;                     /* the RAM tape (it can be written) */
} tape_view_t;

typedef struct {                     /* a decoded block */
    int16_t s[TAPE_BLK + 1u];        /* + the next block's first sample */
    uint16_t blk;
    uint8_t ok;
} tape_rd_t;

typedef struct {                     /* ISR only */
    tape_rd_t a, b;                  /* the head's block; the old head's while a jump fades */
    int16_t stage[TAPE_BLK];         /* the writer's block, decoded and being mixed */
    int32_t pos;                     /* the head, in samples Q12 (22.05 kHz units) */
    int32_t xpos;                    /* the old head during a fade */
    int32_t xf, xflen;               /* the fade: output samples left, its length */
    int32_t stop_at;                 /* a slice played while stopped ends here (samples), -1: no end */
    int32_t amp;                     /* start/stop ramp, Q15 */
    int32_t wlast;                   /* the last sample written, -1: none */
    uint16_t wblk;                   /* the staged block */
    uint8_t wstaged;                 /* stage holds wblk */
    uint8_t running;                 /* the head moves */
    uint8_t was_playing;
    uint32_t keys_prev;
} tape_rt_t;
static tape_rt_t tape_rt[NTRK] __attribute__((section(".pool")));

/* the clear's undo: one, for the last clear, until REC writes over it */
static struct {
    uint8_t valid, trk, src, empty;
} tape_undo;

/* a gain in dB (-24..24) as Q10: 2x per 6 dB, straight between */
static int32_t db_q10(int32_t db)
{
    int32_t f = 1024;
    for (; db >= 6; db -= 6)
        f *= 2;
    for (; db <= -6; db += 6)
        f /= 2;
    return db >= 0 ? f + f * db / 6 : f - f * (-db) / 12;
}

/* ------------------------------------------------------------- codec --- */
static const int16_t IMA_STEP[89] = {
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31, 34, 37, 41, 45, 50, 55, 60, 66, 73, 80, 88, 97,
    107, 118, 130, 143, 157, 173, 190, 209, 230, 253, 279, 307, 337, 371, 408, 449, 494, 544, 598, 658, 724, 796,
    876, 963, 1060, 1166, 1282, 1411, 1552, 1707, 1878, 2066, 2272, 2499, 2749, 3024, 3327, 3660, 4026, 4428, 4871,
    5358, 5894, 6484, 7132, 7845, 8630, 9493, 10442, 11487, 12635, 13899, 15289, 16818, 18500, 20350, 22385, 24623,
    27086, 29794, 32767};
static const int8_t IMA_IDX[8] = {-1, -1, -1, -1, 2, 4, 6, 8};

/* one nibble into the decoder state */
static inline int32_t ima_step(int32_t *pred, int32_t *idx, uint32_t code)
{
    int32_t step = IMA_STEP[*idx], vd = step >> 3, p;
    if (code & 4u)
        vd += step;
    if (code & 2u)
        vd += step >> 1;
    if (code & 1u)
        vd += step >> 2;
    p = (code & 8u) ? *pred - vd : *pred + vd;
    *pred = clamp(p, -32768, 32767);
    *idx = clamp(*idx + IMA_IDX[code & 7u], 0, 88);
    return *pred;
}

/* n samples of a block (from its stored state) into out */
static void ima_dec(const uint8_t *data, int32_t pred, int32_t idx, int16_t *out, uint32_t n)
{
    uint32_t i;
    for (i = 0; i < n; i++)
        out[i] = (int16_t)ima_step(&pred, &idx, (data[i >> 1] >> ((i & 1u) * 4u)) & 15u);
}

/* n samples into a block, from the state (*pred, *idx), which is left at the block's end: the encoder
 * tools/gen_reels.py runs */
static void ima_enc_st(const int16_t *in, int32_t *pst, int32_t *ist, uint8_t *data, uint32_t n)
{
    int32_t pred = *pst, idx = *ist;
    uint32_t i;
    for (i = 0; i < n; i++) {
        int32_t step = IMA_STEP[idx], diff = in[i] - pred, code = 0;
        if (diff < 0) {
            code = 8;
            diff = -diff;
        }
        if (diff >= step) {
            code |= 4;
            diff -= step;
        }
        if (diff >= step >> 1) {
            code |= 2;
            diff -= step >> 1;
        }
        if (diff >= step >> 2)
            code |= 1;
        ima_step(&pred, &idx, (uint32_t)code);
        if (i & 1u)
            data[i >> 1] = (uint8_t)((data[i >> 1] & 15u) | ((uint32_t)code << 4));
        else
            data[i >> 1] = (uint8_t)code;
    }
    *pst = pred;
    *ist = idx;
}

static void ima_enc(const int16_t *in, int32_t pred, int32_t idx, uint8_t *data, uint32_t n)
{
    ima_enc_st(in, &pred, &idx, data, n);
}

/* -------------------------------------------------------------- views --- */
static int uslot_view(uint32_t s, tape_view_t *v);   /* reel.c: a user reel in flash */

/* what a track has chosen: 0 its RAM tape, 1..NREEL a factory reel, then the user reels */
static uint32_t tape_src(uint32_t t) { return (uint32_t)clamp(tp[t].dev[DEV_SRC][TK_REEL], 0, (int32_t)(NREEL + USLOT_N)); }

static void tape_view(uint32_t t, tape_view_t *v)
{
    uint32_t s = tape_src(t);
    if (s > NREEL) {                                   /* a user reel (an empty slot plays nothing) */
        if (!uslot_view(s - NREEL - 1u, v)) {
            v->len = 0;
            v->ram = 0;
            v->data = tape_ram[t].data;                /* (never read: len 0) */
            v->pred = tape_ram[t].pred;
            v->idx = tape_ram[t].idx;
            v->peak = tape_ram[t].peak;
        }
        return;
    }
    if (s) {
        const reel_t *r = &REELS[s - 1u];
        v->data = r->data;
        v->pred = r->pred;
        v->idx = r->idx;
        v->peak = r->peak;
        v->len = r->nblk * TAPE_BLK;
        v->ram = 0;
        return;
    }
    v->data = tape_ram[t].data;
    v->pred = tape_ram[t].pred;
    v->idx = tape_ram[t].idx;
    v->peak = tape_ram[t].peak;
    v->len = tape_ctl[t].empty ? 0u : tape_ctl[t].nblk * TAPE_BLK;
    v->ram = 1;
}

/* the loop window in samples: STRT and LEN in % of what the track plays (at least one block long) */
static void tape_window(uint32_t t, uint32_t len, int32_t *ls, int32_t *ll)
{
    const int16_t *k = tp[t].dev[DEV_SRC];
    int32_t s = (int32_t)len * k[TK_STRT] / 100, l = (int32_t)len * k[TK_LEN] / 100;
    if (l < (int32_t)TAPE_BLK)
        l = (int32_t)TAPE_BLK;
    if (s + l > (int32_t)len)
        s = (int32_t)len - l;
    *ls = s < 0 ? 0 : s;
    *ll = l > (int32_t)len ? (int32_t)len : l;
}

/* the head's step per output sample, Q12 of a tape sample: 0.5 at 100 % (22.05 kHz under 44.1 kHz); SPD
 * -200..200 %, REV turns it round, HALF halves it */
static int32_t tape_inc(uint32_t t)
{
    const int16_t *k = tp[t].dev[DEV_SRC];
    int32_t inc = 2048 * k[TK_SPD] / 100;
    if (k[TK_REV])
        inc = -inc;
    return k[TK_HALF] ? inc / 2 : inc;
}

/* sample i of the view through reader r (silence outside it) */
static int32_t tape_at(const tape_view_t *v, tape_rd_t *r, int32_t i)
{
    uint32_t blk, o;
    if (i < 0 || (uint32_t)i >= v->len)
        return 0;
    blk = (uint32_t)i / TAPE_BLK;
    o = (uint32_t)i % TAPE_BLK;
    if (!r->ok || r->blk != blk) {
        ima_dec(v->data + blk * (TAPE_BLK / 2u), v->pred[blk], v->idx[blk], r->s, TAPE_BLK);
        if ((blk + 1u) * TAPE_BLK < v->len) {          /* the next block's first sample */
            int32_t p = v->pred[blk + 1u], x = v->idx[blk + 1u];
            r->s[TAPE_BLK] = (int16_t)ima_step(&p, &x, v->data[(blk + 1u) * (TAPE_BLK / 2u)] & 15u);
        } else {
            r->s[TAPE_BLK] = r->s[TAPE_BLK - 1u];
        }
        r->blk = (uint16_t)blk;
        r->ok = 1;
    }
    return r->s[o];
}

/* the view at head position pos (Q12), interpolated */
static int32_t tape_read(const tape_view_t *v, tape_rd_t *r, int32_t pos)
{
    int32_t i = pos >> 12, f = pos & 4095, a = tape_at(v, r, i), b;
    if (i < 0 || (uint32_t)i >= v->len)
        return 0;
    b = r->s[((uint32_t)i % TAPE_BLK) + 1u];
    return a + (((b - a) * f) >> 12);
}

/* ------------------------------------------------------------- writer --- */
static void tape_commit(uint32_t t)
{
    tape_rt_t *rt = &tape_rt[t];
    tape_ram_t *m = &tape_ram[t];
    uint32_t b = rt->wblk, i;
    int32_t pk = 0;
    if (!rt->wstaged)
        return;
    rt->wstaged = 0;
    if (tape_ctl[t].empty)                             /* cleared meanwhile: drop it */
        return;
    {   /* the block starts where its new sound does: the decoder state from its first sample and first move (from
         * the old sound's state, every recorded block began wrong until the encoder caught up: a click a block) */
        int32_t d = rt->stage[1] - rt->stage[0], id = 0;
        d = d < 0 ? -d : d;
        while (id < 88 && IMA_STEP[id] < d)
            id++;
        m->pred[b] = rt->stage[0];
        m->idx[b] = (uint8_t)id;
    }
    ima_enc(rt->stage, m->pred[b], m->idx[b], m->data + b * (TAPE_BLK / 2u), TAPE_BLK);
    for (i = 0; i < TAPE_BLK; i++) {
        int32_t a = rt->stage[i] < 0 ? -rt->stage[i] : rt->stage[i];
        if (a > pk)
            pk = a;
    }
    m->peak[b] = (uint8_t)(pk >> 7 > 255 ? 255 : pk >> 7);
    tape_ver[t]++;
    if (rt->a.blk == b)                                /* readers decode the new block from now on */
        rt->a.ok = 0;
    if (rt->b.blk == b)
        rt->b.ok = 0;
}

/* sample i of the RAM tape becomes old x dub + in */
static void tape_write(uint32_t t, int32_t i, int32_t in, int32_t dub)
{
    tape_rt_t *rt = &tape_rt[t];
    tape_ram_t *m = &tape_ram[t];
    uint32_t b = (uint32_t)i / TAPE_BLK;
    if (!rt->wstaged || rt->wblk != b) {
        tape_commit(t);
        ima_dec(m->data + b * (TAPE_BLK / 2u), m->pred[b], m->idx[b], rt->stage, TAPE_BLK);
        rt->wblk = (uint16_t)b;
        rt->wstaged = 1;
    }
    rt->stage[(uint32_t)i % TAPE_BLK] = (int16_t)clamp(rt->stage[(uint32_t)i % TAPE_BLK] * dub / 100 + in, -32767, 32767);
}

/* ------------------------------------------------------------ the head --- */
/* jump the head to pos, the old head fading out over the fade (FADE, or at least TAPE_DECLICK) */
static void tape_jump(uint32_t t, int32_t pos)
{
    tape_rt_t *rt = &tape_rt[t];
    int32_t fl = tp[t].dev[DEV_SRC][TK_FADE] * 441 / 10;   /* ms -> output samples */
    rt->xpos = rt->pos;
    rt->b.ok = 0;
    rt->xflen = rt->xf = fl > TAPE_DECLICK ? fl : TAPE_DECLICK;
    rt->pos = pos;
}

/* white key k: play from slice k of the loop (16 slices); stopped, play just that slice (backwards from its end
 * when the tape runs in reverse) */
static void tape_slice(uint32_t t, uint32_t k, int32_t ls, int32_t ll, int32_t inc)
{
    tape_rt_t *rt = &tape_rt[t];
    int32_t s0 = ls + ll * (int32_t)k / 16, s1 = ls + ll * ((int32_t)k + 1) / 16;
    tape_jump(t, (inc < 0 ? s1 - 1 : s0) << 12);
    if (!sys.playing) {
        rt->running = 1;
        rt->stop_at = inc < 0 ? s0 : s1;
    }
}

/* audio ISR: n output samples of track t (mono Q15, before level) into out; keys: the white keys held on this
 * track; rec_in: what REC records (n samples), 0 when not recording */
static void tape_block(uint32_t t, uint32_t keys, const int32_t *rec_in, int32_t *out, uint32_t n)
{
    tape_rt_t *rt = &tape_rt[t];
    tape_view_t v;
    int32_t ls, ll, inc = tape_inc(t), i, dub = tp[t].dev[DEV_SRC][TK_DUB], gain = db_q10(tp[t].dev[DEV_SRC][TK_GAIN]);
    uint32_t k, press = keys & ~rt->keys_prev, playing = sys.playing;
    int rec = rec_in && tape_ctl[t].rec_ok && tape_src(t) == 0u;
    tape_view(t, &v);
    tape_window(t, v.len ? v.len : TAPE_LEN, &ls, &ll);
    rt->keys_prev = keys;
    if (playing != rt->was_playing) {                  /* the transport: all heads from the loop's start */
        rt->was_playing = (uint8_t)playing;
        if (playing) {
            rt->pos = (inc < 0 ? ls + ll - 1 : ls) << 12;
            rt->xf = 0;
            rt->running = 1;
            rt->stop_at = -1;
        } else {
            rt->running = 0;                           /* (the ramp fades it) */
        }
    }
    for (k = 0; press && k < NWHITE; k++)                /* a new key: its slice (the lowest, one per block) */
        if ((press >> k) & 1u) {
            tape_slice(t, k, ls, ll, inc);
            break;
        }
    if (!rec && rt->wstaged)
        tape_commit(t);                                /* REC let go: the last block */
    for (i = 0; i < (int32_t)n; i++) {
        int32_t s = 0, tgt = rt->running ? 32767 : 0;
        rt->amp += rt->amp < tgt ? 372 : rt->amp > tgt ? -372 : 0;   /* ~2 ms either way */
        rt->amp = clamp(rt->amp, 0, 32767);
        if (rt->amp) {
            s = tape_read(&v, &rt->a, rt->pos);
            if (rt->xf > 0) {                          /* the old head fading out */
                int32_t o = tape_read(&v, &rt->b, rt->xpos);
                s = (s * (rt->xflen - rt->xf) + o * rt->xf) / rt->xflen;
                rt->xpos += inc;
                rt->xf--;
            }
            s = (s * rt->amp) >> 15;
        }
        out[i] = s;
        if (!rt->running)
            continue;
        if (rec && playing) {                          /* REC: every tape sample the head passes */
            int32_t a = rt->pos >> 12, w = rt->wlast < 0 ? a : rt->wlast, in = rec_in[i] * gain >> 10;
            if (w != a) {
                int32_t d = a > w ? 1 : -1;
                for (w += d; w != a + d; w += d)
                    if (w >= 0 && w < (int32_t)v.len)
                        tape_write(t, w, in, dub);
            } else if (rt->wlast < 0 && a >= 0 && a < (int32_t)v.len) {
                tape_write(t, a, in, dub);
            }
            rt->wlast = a;
        } else {
            rt->wlast = -1;
        }
        rt->pos += inc;
        if (rt->stop_at >= 0 && (inc >= 0 ? rt->pos >> 12 >= rt->stop_at : rt->pos >> 12 < rt->stop_at)) {
            rt->running = 0;                           /* a slice played while stopped: its end */
            rt->stop_at = -1;
        } else if (inc >= 0 && rt->pos >= (ls + ll) << 12) {
            tape_jump(t, rt->pos - (ll << 12));        /* the seam, crossfaded */
            rt->wlast = -1;
        } else if (inc < 0 && rt->pos < ls << 12) {
            tape_jump(t, rt->pos + (ll << 12));
            rt->wlast = -1;
        }
    }
}

/* ----------------------------------------------------- main loop side --- */
static void tape_init(void)
{
    uint32_t t;
    for (t = 0; t < NTRK; t++) {
        tape_rt[t].wlast = -1;
        tape_rt[t].stop_at = -1;
        tape_ctl[t].nblk = 0;
        tape_ctl[t].empty = 0;
    }
}

/* REC armed on track t: make its RAM tape ready to be written. A reel is copied in (REEL turns to TAPE); a cleared
 * or unused tape starts silent at full length. Returns 0, and leaves REC off, when a reel would overwrite a RAM tape
 * that holds a take (clear it, or set REEL to TAPE, first). */
static int tape_prepare(uint32_t t)
{
    tape_ram_t *m = &tape_ram[t];
    tape_ctl_t *c = &tape_ctl[t];
    uint32_t s = tape_src(t), b;
    if (c->rec_ok)
        return 1;
    if (s) {                                           /* a reel (factory or yours): copied onto the tape */
        tape_view_t v;
        uint32_t nb;
        if (c->nblk && !c->empty)
            return 0;
        tape_view(t, &v);
        nb = v.len / TAPE_BLK;
        if (!nb)                                       /* an empty user slot: record onto a blank tape */
            goto blank;
        for (b = 0; b < nb * (TAPE_BLK / 2u); b++)
            m->data[b] = v.data[b];
        for (b = 0; b < nb; b++) {
            m->pred[b] = v.pred[b];
            m->idx[b] = v.idx[b];
            m->peak[b] = v.peak[b];
        }
        c->nblk = (uint16_t)nb;
        c->empty = 0;
        tp[t].dev[DEV_SRC][TK_REEL] = 0;               /* the track plays its tape (the same sound) */
    } else if (c->empty || !c->nblk) {
    blank:
        tp[t].dev[DEV_SRC][TK_REEL] = 0;
        for (b = 0; b < TAPE_LEN / 2u; b++)
            m->data[b] = 0;                            /* (zero nibbles from 0, 0: silence) */
        for (b = 0; b < TAPE_NBLK; b++) {
            m->pred[b] = 0;
            m->idx[b] = 0;
            m->peak[b] = 0;
        }
        c->nblk = TAPE_NBLK;
        c->empty = 0;
    }
    if (tape_undo.valid && tape_undo.trk == t)         /* the cleared take is gone now */
        tape_undo.valid = 0;
    c->rec_ok = 1;
    tape_ver[t]++;
    return 1;
}

static void tape_unprepare(uint32_t t) { tape_ctl[t].rec_ok = 0; }

/* the POLY key held: clear what track t plays (a reel: the track goes back to its tape, cleared) */
static void tape_clear(uint32_t t)
{
    tape_ctl[t].rec_ok = 0;
    tape_undo.valid = 1;
    tape_undo.trk = (uint8_t)t;
    tape_undo.src = (uint8_t)tape_src(t);
    tape_undo.empty = tape_ctl[t].empty;
    tp[t].dev[DEV_SRC][TK_REEL] = 0;
    tape_ctl[t].empty = 1;
    tape_ver[t]++;
}

/* SAVE held: undo the last clear, while nothing has been recorded over it; returns the track, or -1 */
static int32_t tape_undo_clear(void)
{
    uint32_t t = tape_undo.trk;
    if (!tape_undo.valid)
        return -1;
    tape_undo.valid = 0;
    tape_ctl[t].empty = tape_undo.empty;
    tp[t].dev[DEV_SRC][TK_REEL] = tape_undo.src;
    tape_ver[t]++;
    return (int32_t)t;
}

/* for the screen: the peak (0..1000) of what track t plays at pos (0..1000 of it), and where its head is (0..1000;
 * -1 when it isn't running) */
static int32_t tape_peak_at(uint32_t t, int32_t pos)
{
    tape_view_t v;
    uint32_t b;
    tape_view(t, &v);
    if (!v.len)
        return 0;
    b = (uint32_t)clamp(pos, 0, 999) * (v.len / TAPE_BLK) / 1000u;
    return v.peak[b] * 1000 / 255;
}

static int32_t tape_head(uint32_t t)
{
    tape_view_t v;
    tape_view(t, &v);
    if (!tape_rt[t].running || !v.len)
        return -1;
    return clamp((tape_rt[t].pos >> 12) * 1000 / (int32_t)v.len, 0, 1000);
}

/* the length of what track t plays, in ms (0: nothing) */
static int32_t tape_ms(uint32_t t)
{
    tape_view_t v;
    tape_view(t, &v);
    return (int32_t)(v.len * 10u / (TAPE_SR / 100u));
}

/* the name of what track t plays: a reel's, TAPE, or EMPTY */
static const char *tape_name(uint32_t t)
{
    uint32_t s = tape_src(t);
    if (s > NREEL)
        return uslot_name[s - NREEL - 1u];
    return s ? REELS[s - 1u].name : tape_ctl[t].empty || !tape_ctl[t].nblk ? "EMPTY" : "TAPE";
}
