/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 Leo Kuroshita (@kurogedelic), Hügelton Instruments */
/* Felucca menu (HOME held): a list that scrolls (MENU_VIS rows shown, the selected one kept in the middle: no state),
 * grouped: the screen (COLOR, STYLE, LARGE, ANIM, LEDS), the controls (HOLD: the layer threshold, KNOB ACCEL, FX LATCH,
 * BPM LOCK), the sound (SPEAKER EQ: FLAT LOWCUT BASS+, USB LEVEL), USB SERIAL, then CALIBRATION (the setup screen: HARDWARE
 * CALIBRATION) and ABOUT. No BACK row: OCT- is back.
 * The two-valued rows are bits of ui_prefs (MENU_FLAGS). PRESETS scrolls from ABOUT through all credits.
 * ui.menu: 1 list, 2 information. */
/* ------------------------------------------------------------ menu --- */
enum { MI_COLOR, MI_STYLE, MI_LARGE, MI_ANIM, MI_LEDS, MI_HOLD, MI_ACCEL, MI_LATCH, MI_BPMLOCK, MI_LOWCUT, MI_USB, MI_SERIAL, MI_PANEL, MI_ABOUT, MI_COUNT };
static const char *const MI_NAME[MI_COUNT] = {"COLOR", "STYLE", "LARGE", "ANIM", "LEDS", "HOLD", "KNOB ACCEL", "FX LATCH", "BPM LOCK",
                                              "SPEAKER EQ", "USB LEVEL", "USB SERIAL", "CALIBRATION", "ABOUT"};
/* STYLE (ui_style, gfx.c ST_*): FLAT the filled cards; LINE black areas divided by 1 px rules (#50, #57: the 0.9 look)
 * (1.0.2: PIXEL retired, a saved PIXEL reads as LINE) */
static const char *const STYLE_N[2] = {"FLAT", "LINE"};
/* the two-valued rows: a bit of ui_prefs and its names (bit clear = the default, bit set); KNOB 1 right = set
 * (the other value), left = clear (the default) */
typedef struct { uint8_t row, bit; const char *name[2]; } menu_flag_t;
static const menu_flag_t MENU_FLAGS[] = {
    {MI_LARGE, PREF_LARGE, {"OFF", "ON"}},            /* #15 / Discussion #80: ON, big knob labels and values (ui.c large_kind) */
    {MI_ANIM, PREF_ANIM_OFF, {"ON", "OFF"}},          /* #46: OFF, values snap (ui_draw.c roll_note, ui_graph.c pr_follow) */
    {MI_ACCEL, PREF_ACCEL, {"OFF", "ON"}},            /* #52: ui_input.c accel */
    {MI_LATCH, PREF_LATCH, {"OFF", "ON"}},
    {MI_USB, PREF_USB_FIXED, {"MASTER", "FIXED"}},     /* fx.c fx_usb_fixed: FIXED, USB at the full level */
    {MI_BPMLOCK, PREF_BPM_LOCK, {"OFF", "ON"}},        /* #58: ON, SELECT sets the tempo with GLO held only (ui_input.c) */
    {MI_SERIAL, PREF_SERIAL_OFF, {"ON", "OFF"}},       /* #67: OFF, no serial console (usb_serial_apply) */
};
/* MENU > USB SERIAL (#67). The serial console is a developer tool (README: FELUCCA_CDC). ON (the default) presents it,
 * the descriptors byte for byte as before; OFF re-enumerates as audio + MIDI only, device class 0 (the bytes of a
 * FELUCCA_CDC=0 build): macOS 13-15 then attach their USB audio driver (with the console Apple's CDC composite driver
 * takes the device and the audio input never appears). USB-MIDI stays, and with it the editor, the update installer
 * and the soft key (SysEx on EP1). Applied at boot before USB starts (main.c: enumerated with it from the start, never
 * on then off) and while the menu is closed (ui_input: one re-enumeration when it closes, not one per KNOB 1 step) */
static void usb_serial_apply(void)
{
#if FELUCCA_CDC
    usb_cdc_switch(FELUCCA_CDC_DEFAULT && !(ui_prefs & PREF_SERIAL_OFF));   /* (a FELUCCA_CDC_DEFAULT=0 build: off) */
#endif
}
static const menu_flag_t *menu_flag(uint32_t row)
{
    uint32_t i;
    for (i = 0; i < NELEM(MENU_FLAGS); i++)
        if (MENU_FLAGS[i].row == row)
            return &MENU_FLAGS[i];
    return 0;
}
/* SPEAKER EQ (settings.lowcut, fx.c fx_lowcut): an EQ on the master for the small speaker, not a speaker switch
 * (#42: "OFF" read as the speaker off). FLAT is the old OFF (0, stored as before). The built-in speaker cannot be
 * turned off from the firmware (no amp enable or mute line is known); the EQ reaches
 * the headphone / line out and USB audio too (one DAC, uac_tap reads the master) */
static const char *const SPK_EQ[3] = {"FLAT", "LOWCUT", "BASS+"};

/* https://hugelton.github.io/Felucca, QR version 3, correction M, generated by CoreImage.
 * One row per word, leftmost module in bit 0; the constant matrix needs no encoder or RAM. */
static const uint32_t ABOUT_QR[29] = {
    0x1FCD247Fu, 0x1059C541u, 0x1745765Du, 0x1758E85Du, 0x174E575Du, 0x104C3A41u,
    0x1FD5557Fu, 0x000B7000u, 0x091BCA55u, 0x1270DC8Au, 0x1DB4375Au, 0x083E9FA1u,
    0x1A63124Eu, 0x12513981u, 0x1AE2524Du, 0x0A2E78A0u, 0x1A7F4FC3u, 0x167154B0u,
    0x19A228D5u, 0x0A561C2Au, 0x01F10B4Du, 0x1D1B3F00u, 0x1B5A467Fu, 0x1B13F641u,
    0x11F24D5Du, 0x1D1B625Du, 0x1389315Du, 0x08DFD641u, 0x1813977Fu,
};

static void draw_about_qr(int32_t x, int32_t y)
{
    uint32_t row, col;
    cv_rect(x, y, 74, 74, UI_QR_LIGHT);             /* fixed light / dark, independent of the palette */
    for (row = 0; row < 29u; row++)
        for (col = 0; col < 29u; col++)
            if ((ABOUT_QR[row] >> col) & 1u)
                cv_rect(x + 8 + (int32_t)col * 2, y + 8 + (int32_t)row * 2, 2, 2, UI_QR_DARK);
}

/* All notices are in flash. Wrap at the font's actual width, without dropping URL
 * characters; the same layout computes the scroll limit and draws clipped bands.
 * Mixed case here (long text); S throughout, the title in L. */
#define MENU_DOC_H 196                                /* the document: screen rows 24..220 */
enum { MC_TEXT, MC_TITLE, MC_URL };
typedef struct { const char *text; uint8_t kind; } menu_credit_t;
static const menu_credit_t MENU_CREDITS[] = {
    {"H\xFCgelton Instruments / OWN WORK", MC_TITLE},  /* Felucca's own: above; these are ours too */
    {"Leo Kuroshita", MC_TEXT},
    {"CrispyZebra (PHASE waveforms), the DRUM voices, the Sample Pack: GPL-3.0", MC_TEXT},
    {"Fukiai icon font: MIT", MC_TEXT},
    {"https://github.com/hugelton", MC_URL},
    {"", MC_TEXT},
    {"KLATTSCH / VOICE REFERENCE", MC_TITLE},
    {"Tony Gies / MIT", MC_TEXT},
    {"https://github.com/tgies/klattsch", MC_URL},
    {"", MC_TEXT},
    {"DAISYSP / PHYS PORT", MC_TITLE},
    {"Electrosmith, Emilie Gillet", MC_TEXT},
    {"MIT", MC_TEXT},
    {"https://github.com/electro-smith/DaisySP", MC_URL},
    {"", MC_TEXT},
    {"DEXED + MSFA / FM6 PORT", MC_TITLE},
    {"Pascal Gauthier, Google Inc.", MC_TEXT},
    {"msfa: Apache-2.0, Dexed: GPL-3.0", MC_TEXT},
    {"https://github.com/asb2m10/dexed", MC_URL},
    {"", MC_TEXT},
    {"RINGS / PHYS PORT", MC_TITLE},
    {"Emilie Gillet / MIT", MC_TEXT},
    {"https://github.com/pichenettes/eurorack", MC_URL},
    {"", MC_TEXT},
    {"INTER TIGHT / FONT", MC_TITLE},
    {"The Inter Project Authors", MC_TEXT},
    {"SIL Open Font License 1.1", MC_TEXT},
    {"https://github.com/rsms/inter-tight", MC_URL},
    {"", MC_TEXT},
    {"VSCO-2 CE + VCSL / SAMPLES", MC_TITLE},
    {"Versilian Studios / CC0 1.0", MC_TEXT},
    {"https://github.com/sgossner/VSCO-2-CE", MC_URL},
    {"https://github.com/sgossner/VCSL", MC_URL},
    {"", MC_TEXT},
    {"VOICE / RESEARCH", MC_TITLE},
    {"Dennis H. Klatt (1980)", MC_TEXT},
    {"https://doi.org/10.1121/1.383940", MC_URL},
    {"Hillenbrand, Getty, Clark and Wheeler (1995)", MC_TEXT},
    {"https://doi.org/10.1121/1.411872", MC_URL},
};

static int32_t menu_text(const char *s, int32_t y, uint16_t col, int draw)
{
    while (*s) {
        char line[64];
        uint32_t n = 0, space = 0, take, prev = 0;
        int32_t pen = 0;                                 /* 1/16 px, as text_w adds it up */
        while (s[n] && n < sizeof line - 1u) {
            uint32_t c = (uint8_t)s[n];
            line[n] = s[n];
            line[n + 1u] = 0;
            pen += (prev ? kern(&AF_S, prev, c) : 0) + AF_S.g[glyph(&AF_S, c)].adv;
            prev = c;
            if ((pen + 8) >> 4 > 226)
                break;
            if (s[n] == ' ')
                space = n;
            n++;
        }
        take = s[n] && space ? space : n;
        if (!take) take = 1;                         /* progress even for an unusually wide glyph */
        line[take] = 0;
        if (draw && y + AF_S.h > 0 && y < MENU_DOC_H)
            cv_text(6, y, &AF_S, line, col);
        y += 18;
        s += take;
        while (*s == ' ') s++;
    }
    return y;
}

static int32_t menu_document(int32_t y, int draw)
{
    uint32_t i;
    if (draw) {
        cv_text(6, y + 2, &AF_L, "FELUCCA", T_THEME);
        cv_text(6, y + 38, &AF_S, "Multi-engine synthesizer", T_TEXT);
        cv_text(6, y + 58, &AF_M, FELUCCA_VERSION, T_THEME);
        cv_text_r(232, y + 61, &AF_S, __DATE__, T_MID, T_BG);
        cv_text(6, y + 82, &AF_S, "(C) 2026 Leo Kuroshita", T_TEXT);
        cv_text(6, y + 100, &AF_S, "H\xFCgelton Instruments", T_TEXT);
        cv_text(6, y + 118, &AF_S, "GPL-3.0-only", T_TEXT);
        cv_text(6, y + 138, &AF_S, "hugelton.github.io", T_MID);
        cv_text(6, y + 156, &AF_S, "/Felucca", T_MID);
        cv_text(6, y + 180, &AF_S, "hugelton.com", T_MID);
        draw_about_qr(158, y + 122);
    }
    y = menu_text("CREDITS", y + 216, T_THEME, draw) + 8;
    for (i = 0; i < NELEM(MENU_CREDITS); i++) {
        const menu_credit_t *c = &MENU_CREDITS[i];
        const char *text = c->text;
        /* Display host/path once; the full source URL stays in the flash table. */
        if (c->kind == MC_URL && str_len(text) >= 8u && !memcmp(text, "https://", 8))
            text += 8;
        if (!text[0]) y += 8;
        else y = menu_text(text, y, c->kind == MC_TITLE ? T_THEME : c->kind == MC_URL ? T_MID : T_TEXT, draw);
    }
    y = menu_text("LICENSES + SOURCE", y + 12, T_THEME, draw);
    y = menu_text("DRUM + own samples: GPL-3.0-only", y, T_TEXT, draw);
    y = menu_text("Fonts and icons: their licences travel with the source and the release files.", y, T_TEXT, draw);
    y = menu_text("NO WARRANTY", y, T_TEXT, draw);
    y = menu_text("Full notices in source:", y + 8, T_TEXT, draw);
    y = menu_text("github.com/hugelton/Felucca", y, T_MID, draw);
    return y + 4;
}
static int32_t menu_scroll_max(void)
{
    int32_t h = menu_document(0, 0);
    return h > MENU_DOC_H ? h - MENU_DOC_H : 0;
}

/* the menu's header (0..24): its icon and title, the REC mark, the way back */
static void menu_head(void)
{
    cv_begin(240, H_HEAD, T_BG);
    GFX_HOOK_ALIGN(0, HEAD_MY + AF_M_CAP_Y, 0, HEAD_MY + AF_M_CAP_Y + AF_M_CAP_H, AL_V, "header icon on its title's line");
    cv_icon_mid(8, H_HEAD / 2, 16, ui.menu == 2 ? ICON_X_INFO : ICON_X_COG, T_THEME, T_BG);   /* (as draw_head's) */
    GFX_HOOK_ALIGN(0, 0, 0, H_HEAD, AL_V, "header text on its middle");
    cv_text(30, HEAD_MY, &AF_M, ui.menu == 2 ? "ABOUT / CREDITS" : "MENU", T_TEXT);
    if (ui.menu >= 2) {                               /* the way back at the right, the REC mark before it (then */
        const char *w = song.rec ? 0 : "BACK";        /* the keycap goes without its word: no room for both) */
        int32_t x = 232 - kh_w(KC_OCTDN, w);
        GFX_HOOK_ALIGN(0, 0, 0, H_HEAD, AL_V, "header text on its middle");
        cv_key_hint(x, HALF_UP(H_HEAD - KC_H), KC_OCTDN, w, 1, T_BG);
        draw_rec_mark(x - 20, T_BG);
    } else {
        draw_rec_mark(178, T_BG);
    }
    cv_blit(0, Y_HEAD);
}

/* the list: 24 px SURF rows 25 px apart from y 30, the selected one THEME with INK;
 * a 16 px icon, the name (S), the value (M) at the right; COLOR shows the palette's five colours.
 * MENU_VIS rows shown from menu_top(), a scroll bar at the right when there are more.
 * Drawn in two bands (the canvas holds 124 rows), split at y 130 between two rows */
#define MENU_Y0 30
#define MENU_ROW 25
#define MENU_SPLIT 130
#define MENU_VIS 7u
#define MENU_R (MI_COUNT > MENU_VIS ? 226 : 232)       /* a row's width (room for the scroll bar) */
static uint32_t menu_top(void)                         /* the first row shown: the selected one in the middle */
{
    uint32_t s = ui.menu_sel;
    if (MI_COUNT <= MENU_VIS || s < MENU_VIS / 2u)
        return 0;
    return s - MENU_VIS / 2u > MI_COUNT - MENU_VIS ? MI_COUNT - MENU_VIS : s - MENU_VIS / 2u;
}
static const khint_t MENU_KEYS[3] = {{KC_PRESETS, "MOVE"}, {KC_OCTUP, "OK"}, {KC_OCTDN, "BACK"}};
static void draw_menu(void)
{
    static const uint16_t ICO[MI_COUNT] = {ICON_X_PALETTE, ICON_SHAPE, ICON_SIZE, ICON_RATE, ICON_X_STAR_O, ICON_X_TIMER, ICON_X_KNOB,
                                           ICON_X_FX, ICON_TEMPO, ICON_X_SPEAKER, ICON_X_USB, ICON_X_DOC, ICON_X_DOCTOR, ICON_X_INFO};
    uint32_t i, pass, top = menu_top(), sig = ui.menu * 7u + ui.menu_sel * 131u + settings.palette * 1009u +
                            settings.lowcut * 7919u + settings_hold * 3511u + settings_leds * 6151u + ui_prefs * 4099u + ui_style * 257u +
                            song.rec * 65537u + song.sel * 13u +
                            (ui.menu == 2 ? ui.menu_scroll * 48611u : 0u);
    if (!ui.force && sig == ui.menu_sig)
        return;
    ui.menu_sig = sig;
    menu_head();
    if (ui.menu >= 2) {
        int32_t scroll = ui.menu_scroll, max = menu_scroll_max();
        int32_t thumb = MENU_DOC_H * MENU_DOC_H / (max + MENU_DOC_H);
        if (thumb < 12) thumb = 12;
        for (pass = 0; pass < 2u; pass++) {
            cv_begin(240, pass ? MENU_DOC_H - 124u : 124u, T_BG);
            cv_oy = pass ? -124 : 0;
            cv_scroll = 1;
            menu_document(-scroll, 1);
            cv_scroll = 0;
            cv_rrect(235, 2, 3, MENU_DOC_H - 4, 1, T_LINE, T_BG);           /* the scroll bar */
            cv_rrect(235, 2 + (max ? scroll * (MENU_DOC_H - 4 - thumb) / max : 0), 3, thumb, 1, T_MID, T_LINE);
            cv_oy = 0;
            cv_blit(0, H_HEAD + pass * 124u);
        }
        cv_begin(240, 240 - (H_HEAD + MENU_DOC_H), T_BG);
        cv_key_hint(8, 4, KC_PRESETS, "SCROLL", 1, T_BG);
        cv_blit(0, H_HEAD + MENU_DOC_H);
        return;
    }
    for (pass = 0; pass < 2u; pass++) {
        int32_t top_y = pass ? MENU_SPLIT : H_HEAD;
        cv_begin(240, (uint32_t)(pass ? 240 - MENU_SPLIT : MENU_SPLIT - H_HEAD), T_BG);
        cv_oy = -top_y;                               /* drawn in screen rows */
        if (ux.style && !pass)                        /* LINE: a rule under the header, one under each row */
            cv_rule(4, (H_HEAD + MENU_Y0 - 2) / 2, MENU_R, 1);
        for (i = top; i < top + MENU_VIS && i < MI_COUNT; i++) {
            int32_t y = MENU_Y0 + (int32_t)(i - top) * MENU_ROW, vr = MENU_R - 4;   /* vr: the values' right edge */
            int32_t ny = y + CAP_IN(S, 24), vy = y + CAP_IN(M, 24);           /* the name, the value: centred */
            int sel = i == ui.menu_sel;
            uint16_t bg = sel ? T_THEME : T_SURF, fg = sel ? T_INK : T_TEXT, val = sel ? T_INK : T_THEME;
            const menu_flag_t *f = menu_flag(i);
            if (y + 24 <= top_y || y >= top_y + (int32_t)cv_h)
                continue;
            cv_rrect(4, y, MENU_R, 24, 6, bg, T_BG);
            if (ux.style)
                cv_rule(4, y + 24, MENU_R, 1);
            GFX_HOOK_ALIGN(0, y, 0, y + 24, AL_V, "menu row icon centred up/down");
            cv_icon_in(12, y, 0, 24, 16, ICO[i], sel ? T_INK : T_MID, bg);
            GFX_HOOK_ALIGN(0, y, 0, y + 24, AL_V, "menu row name centred up/down");
            cv_text_on(36, ny, &AF_S, MI_NAME[i], fg, bg);
            if (f || i == MI_LOWCUT || i == MI_STYLE || i == MI_HOLD || i == MI_LEDS || i == MI_COLOR)
                GFX_HOOK_ALIGN(0, y, 0, y + 24, AL_V, "menu row value centred up/down");
            if (f)
                cv_text_r(vr, vy, &AF_M, f->name[(ui_prefs & f->bit) != 0], val, bg);
            if (i == MI_LOWCUT)
                cv_text_r(vr, vy, &AF_M, SPK_EQ[settings.lowcut % 3u], val, bg);
            if (i == MI_STYLE)
                cv_text_r(vr, vy, &AF_M, STYLE_N[ui_style & 1u], val, bg);
            if (i == MI_HOLD) {                         /* "0.4" and its unit */
                char b[8] = "0.4";
                b[2] = (char)('0' + HOLD_MS[settings_hold % 4u] / 100u);
                GFX_HOOK_ALIGN(0, 0, 0, vy + AF_M.asc, AL_B, "menu row unit on its value's baseline");
                cv_text_r(cv_text_r(vr, vy + AF_M.asc - AF_S.asc, &AF_S, "s", val == T_INK ? T_INK : T_MID, bg) - 3, vy, &AF_M, b,
                          val, bg);
            }
            if (i == MI_LEDS)
                cv_text_r(vr, vy, &AF_M, LEDS_NAME[settings_leds % LEDS_COUNT], val, bg);
            if (i == MI_COLOR) {
                uint32_t k;
                const uint16_t *tok = &T_BG;            /* BG SURF TEXT THEME ACCENT */
                int32_t x0 = vr - 76;
                cv_text_r(x0 - 6, vy, &AF_M, UI_PALETTES[settings.palette % NPALETTES].name, val, bg);
                for (k = 0; k < 5u; k++) {
                    cv_rrect(x0 + (int32_t)k * 15, y + 6, 12, 12, 3, T_RAISE, bg);     /* a rim for the dark ones */
                    cv_rrect(x0 + 1 + (int32_t)k * 15, y + 7, 10, 10, 2, tok[k], T_RAISE);
                }
            }
        }
        if (MI_COUNT > MENU_VIS) {                      /* the scroll bar: the rows shown, of all */
            int32_t h = (int32_t)(MENU_VIS * MENU_ROW) - 1, th = h * (int32_t)MENU_VIS / (int32_t)MI_COUNT;
            cv_rrect(234, MENU_Y0, 3, h, 1, T_LINE, T_BG);
            cv_rrect(234, MENU_Y0 + (h - th) * (int32_t)top / (int32_t)(MI_COUNT - MENU_VIS), 3, th, 1, T_MID, T_LINE);
        }
        cv_key_row(8, 232, 207, MENU_KEYS, 3, 7u, T_BG);
        cv_oy = 0;
        cv_blit(0, (uint32_t)top_y);
    }
}
static void enc_drop(void)                             /* knob turns nobody takes */
{
    uint32_t k;
    for (k = 0; k < NE; k++)
        panel_enc(k);
}

static void menu_close(void)
{
    settings_save();                                   /* palette / panel table, if changed */
    ui.menu = 0;
    ui.force = 1;
    go_home();
}

/* menu: PRESETS moves, OCT+ confirms, OCT- cancels (ABOUT -> list -> close) */
static void menu_input(uint32_t oct)                  /* oct: ui_input.c oct_taps */
{
    int32_t s;
    uint32_t ok = (oct >> 1) & 1u, back = oct & 1u;
    if (back) {
        if (ui.menu >= 2)
            ui.menu = 1, ui.force = 1;
        else
            menu_close();
        return;
    }
    if ((s = panel_enc(EN_PRESET)) != 0 && ui.menu == 1)
        ui.menu_sel = (uint8_t)((ui.menu_sel + (s > 0 ? 1u : MI_COUNT - 1u)) % MI_COUNT);
    else if (s != 0 && ui.menu >= 2) {             /* bounded document scrolling */
        ui.menu_scroll = (uint16_t)clamp((int32_t)ui.menu_scroll + clamp(s, -128, 128) * 18, 0, menu_scroll_max());
    }
    s = panel_enc(EN_K1);
    if (s != 0 && ui.menu == 1 && ui.menu_sel == MI_COLOR) {
        settings.palette = (settings.palette + (s > 0 ? 1u : NPALETTES - 1u)) % NPALETTES;   /* (wraps) */
        palette_set(settings.palette);              /* (the menu signature redraws) */
        ui.force = 1;
    }
    if ((s != 0 || ok) && ui.menu == 1 && ui.menu_sel == MI_LOWCUT) {
        /* KNOB 1 steps FLAT LOWCUT BASS+, OCT+ steps and wraps */
        uint32_t *v = &settings.lowcut, top = 2u;
        *v = s > 0 ? (*v < top ? *v + 1u : top) : s < 0 ? (*v ? *v - 1u : 0u) : (*v < top ? *v + 1u : 0u);
        fx_lowcut = (uint8_t)(settings.lowcut % 3u);
        ok = 0;
    }
    if ((s != 0 || ok) && ui.menu == 1 && ui.menu_sel == MI_STYLE) {
        /* KNOB 1: right = LINE, left = FLAT; OCT+ toggles; drawn so from the next frame (ui_draw.c style_apply) */
        ui_style = (uint8_t)(s > 0 ? ST_LINE : s < 0 ? ST_FLAT : ui_style == ST_LINE ? ST_FLAT : ST_LINE);
        ok = 0;
    }
    if ((s != 0 || ok) && ui.menu == 1 && ui.menu_sel == MI_HOLD) {
        /* KNOB 1 steps 0.3 .. 0.6 s, OCT+ steps and wraps */
        uint32_t v = settings_hold % 4u;
        settings_hold = (uint8_t)(s > 0 ? (v < 3u ? v + 1u : 3u) : s < 0 ? (v ? v - 1u : 0u) : (v + 1u) % 4u);
        ok = 0;
    }
    if ((s != 0 || ok) && ui.menu == 1 && ui.menu_sel == MI_LEDS) {
        /* KNOB 1 steps OFF DIM LO DIM HI INV, OCT+ steps and wraps */
        settings_leds = (uint8_t)leds_step(settings_leds, s);
        ok = 0;
    }
    if ((s != 0 || ok) && ui.menu == 1 && menu_flag(ui.menu_sel)) {
        /* KNOB 1: right = the second value (ON), left = the first (OFF); OCT+ toggles (FX LATCH: the latched
         * effects are off while the menu is up) */
        uint32_t b = menu_flag(ui.menu_sel)->bit;
        ui_prefs = (uint8_t)(s > 0 ? ui_prefs | b : s < 0 ? ui_prefs & ~b : ui_prefs ^ b);
        fx_usb_fixed = (ui_prefs & PREF_USB_FIXED) != 0u;   /* (at once; every frame too: ui_input) */
        ok = 0;
    }
    if (ok && ui.menu == 1) {
        switch (ui.menu_sel) {
        case MI_COLOR:                                 /* OCT+ steps through the palettes too */
            settings.palette = (settings.palette + 1u) % NPALETTES;
            palette_set(settings.palette);
            ui.force = 1;
            break;
        case MI_PANEL:
            panel_setup();
            ui.force = 1;
            break;
        case MI_ABOUT:
            ui.menu = 2;
            ui.menu_scroll = 0;
            ui.force = 1;
            break;
        default:
            menu_close();
            break;
        }
    }
    enc_drop();                                        /* swallow the rest while the menu is up */
}
