/* SPDX-License-Identifier: GPL-3.0-only */
/* Bryo: the dot grid. The main screens are drawn on a 120 x 120 grid of 2 x 2 px dots, in one ink (white on black,
 * fixed for now: the palette setting is kept in the settings record but these screens don't follow it) and a dim
 * ink (45 % of the way from the background), the way a groovebox's OLED reads: bitmap type,
 * 1-dot strokes, dotted guides, solid nodes. Everything here takes dot coordinates on the current canvas; the
 * screen's regions start on even rows, so a region's dot 0 is its first pixel row.
 *
 * The pictograms: one per knob, 22 x 22 dots, and each one IS the value (a dial's pointer, a fader's fill, a
 * slope's length, a keyboard's lit key), so the strip reads without the numbers. The table that picks one per
 * parameter is at the end. Integer only, no float, no 64-bit maths. */

#include "ui_pxfont.h"                /* generated by tools/gen_px_font.py */

#define PX_PICTO 22                   /* a pictogram's box, dots */

static uint16_t px_ink, px_dim, px_bg;

static void px_colors(void)
{
    px_ink = 0xFFFFu;
    px_bg = 0x0000u;
    px_dim = ux_mix(px_bg, px_ink, 45);
}

/* ---------------------------------------------------------- the canvas --- */
/* A strip of the screen is drawn here as dots, 2 bits each (0 the background, 1 dim, 2 ink, 3 a fourth colour: the
 * last other one drawn), and turned into the LCD's pixels only as it's sent: two dot rows at a time into one of two
 * small line buffers, each sent while the other fills. A full-colour canvas of the tallest strip would be 51 KB
 * (Felucca's gfx.c canvas, 59.5 KB, which Bryo no longer uses); this is 1.6 KB of dots and 3.8 KB of lines, and
 * what reaches the LCD is the same, pixel for pixel. */
#define PXC_ROWS 54u                  /* dot rows: the tallest strip, UPDATE MODE's lower 108 px */
static uint8_t pxc[PXC_ROWS][30];     /* 120 dots a row, 4 a byte, the leftmost in the low bits */
static uint32_t pxc_h;                /* the strip's rows */
static uint16_t pxc_pal[4];
static uint16_t pxc_line[2][4u * 240u];   /* 2 dot rows = 4 pixel rows, byte-swapped as the LCD takes them */
static uint32_t pxc_b;                /* the buffer to fill next (the other may still be on its way to the LCD) */

static uint32_t px_code(uint16_t c)
{
    if (c == pxc_pal[2])
        return 2u;
    if (c == pxc_pal[0])
        return 0u;
    if (c == pxc_pal[1])
        return 1u;
    pxc_pal[3] = c;
    return 3u;
}

/* a strip h pixels tall (even: every strip starts and ends on the dot grid), cleared to the background */
static void px_begin(uint32_t h)
{
    uint32_t r, i;
    pxc_h = h / 2u > PXC_ROWS ? PXC_ROWS : h / 2u;
    pxc_pal[0] = px_bg;
    pxc_pal[1] = px_dim;
    pxc_pal[2] = px_ink;
    pxc_pal[3] = px_ink;
    for (r = 0; r < pxc_h; r++)
        for (i = 0; i < 30u; i++)
            pxc[r][i] = 0;
}

static inline void px_set(int32_t x, int32_t y, uint32_t k)
{
    uint8_t *b;
    uint32_t sh;
    if ((uint32_t)x >= 120u || (uint32_t)y >= pxc_h)
        return;
    b = &pxc[y][(uint32_t)x >> 2];
    sh = ((uint32_t)x & 3u) * 2u;
    *b = (uint8_t)((*b & ~(3u << sh)) | (k << sh));
}

static void px_dot(int32_t x, int32_t y, uint16_t c) { px_set(x, y, px_code(c)); }
static void px_box(int32_t x, int32_t y, int32_t w, int32_t h, uint16_t c)
{
    uint32_t k = px_code(c);
    int32_t i, j;
    if (x < 0) {
        w += x;
        x = 0;
    }
    if (y < 0) {
        h += y;
        y = 0;
    }
    if (x + w > 120)
        w = 120 - x;
    if (y + h > (int32_t)pxc_h)
        h = (int32_t)pxc_h - y;
    for (j = 0; j < h; j++)
        for (i = 0; i < w; i++)
            px_set(x + i, y + j, k);
}

/* the strip to the screen at pixel row y (full width) */
static void px_blit(uint32_t y)
{
    uint16_t pal[4];
    uint32_t r, j, x, k;
    for (k = 0; k < 4u; k++)
        pal[k] = (uint16_t)((pxc_pal[k] >> 8) | (pxc_pal[k] << 8));
    for (r = 0; r < pxc_h; r += 2u) {
        uint16_t *o = pxc_line[pxc_b];
        uint32_t rows = pxc_h - r < 2u ? pxc_h - r : 2u;
        for (j = 0; j < rows; j++) {
            const uint8_t *s = pxc[r + j];
            uint16_t *l = o + j * 480u;
            for (x = 0; x < 120u; x++) {
                uint16_t c = pal[(s[x >> 2] >> ((x & 3u) * 2u)) & 3u];
                l[2u * x] = c;
                l[2u * x + 1u] = c;
            }
            for (x = 0; x < 240u; x++)
                l[240u + x] = l[x];
        }
        lcd_blit(0, y + 2u * r, 240, 2u * rows, o);
        pxc_b ^= 1u;
    }
}

/* a line from (x0, y0) to (x1, y1), a dot every step dots along it (1: solid, 2: dotted) */
static void px_line(int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint16_t c, int32_t step)
{
    int32_t dx = x1 > x0 ? x1 - x0 : x0 - x1, dy = y1 > y0 ? y0 - y1 : y1 - y0;
    int32_t sx = x0 < x1 ? 1 : -1, sy = y0 < y1 ? 1 : -1, e = dx + dy, e2, i = 0;
    for (;;) {
        if (i++ % step == 0)
            px_dot(x0, y0, c);
        if (x0 == x1 && y0 == y1)
            break;
        e2 = 2 * e;
        if (e2 >= dy) {
            e += dy;
            x0 += sx;
        }
        if (e2 <= dx) {
            e += dx;
            y0 += sy;
        }
    }
}

static void px_frame(int32_t x, int32_t y, int32_t w, int32_t h, uint16_t c, int32_t step)
{
    px_line(x, y, x + w - 1, y, c, step);
    px_line(x, y + h - 1, x + w - 1, y + h - 1, c, step);
    px_line(x, y, x, y + h - 1, c, step);
    px_line(x + w - 1, y, x + w - 1, y + h - 1, c, step);
}

/* sin of a in 1/64 turn, x1000 (a quarter in 17 entries; mirrored for the rest) */
static int32_t px_sin(int32_t a)
{
    static const int16_t Q[17] = {0, 98, 195, 290, 383, 471, 556, 634, 707, 773, 831, 882, 924, 957, 981, 995, 1000};
    a &= 63;
    return a < 16 ? Q[a] : a < 32 ? Q[32 - a] : a < 48 ? -Q[a - 32] : -Q[64 - a];
}
static int32_t px_cos(int32_t a) { return px_sin(a + 16); }

/* the point r dots from (cx, cy) at a (1/64 turn, 0 = 12 o'clock, clockwise) */
static int32_t px_px(int32_t cx, int32_t r, int32_t a) { return cx + (px_sin(a) * r + (px_sin(a) >= 0 ? 500 : -500)) / 1000; }
static int32_t px_py(int32_t cy, int32_t r, int32_t a) { return cy - (px_cos(a) * r + (px_cos(a) >= 0 ? 500 : -500)) / 1000; }

/* a ring of radius r: 64 points, a dot every step of them (the dotted circles of the dials) */
static void px_ring(int32_t cx, int32_t cy, int32_t r, uint16_t c, int32_t step)
{
    int32_t a;
    for (a = 0; a < 64; a += step)
        px_dot(px_px(cx, r, a), px_py(cy, r, a), c);
}

/* ---------------------------------------------------------------- type --- */
enum { PXF_5, PXF_5B, PXF_3 };       /* 5 x 7, 5 x 7 bold (titles), 3 x 5 */

static uint32_t px_glyph(char ch)
{
    uint32_t c = (uint8_t)ch;
    if (c >= 'a' && c <= 'z')
        c -= 32u;
    return c >= 32u && c < 96u ? c - 32u : '?' - 32u;
}

static int32_t px_adv(uint32_t f) { return f == PXF_3 ? 4 : f == PXF_5B ? 7 : 6; }

static int32_t px_text_w(uint32_t f, const char *s)
{
    int32_t n = (int32_t)str_len(s);
    return n ? n * px_adv(f) - 1 : 0;
}

/* s at (x, y) (its top left), in c; returns the x after it */
static int32_t px_text(int32_t x, int32_t y, uint32_t f, const char *s, uint16_t c)
{
    for (; *s; s++, x += px_adv(f)) {
        uint32_t g = px_glyph(*s), r, b;
        if (f == PXF_3) {
            for (r = 0; r < 5u; r++)
                for (b = 0; b < 3u; b++)
                    if (PX3[g][r] >> (2u - b) & 1u)
                        px_dot(x + (int32_t)b, y + (int32_t)r, c);
            continue;
        }
        for (r = 0; r < 7u; r++) {
            uint32_t row = PX5[g][r];
            if (f == PXF_5B)
                row = row << 1 | row;                    /* bold: each dot doubled to the right, 6 wide */
            for (b = 0; b < 6u; b++)
                if (row >> (5u - b) & 1u)
                    px_dot(x + (int32_t)b - (f == PXF_5B ? 0 : 1), y + (int32_t)r, c);
        }
    }
    return x;
}

static int32_t px_text_c(int32_t x, int32_t w, int32_t y, uint32_t f, const char *s, uint16_t c)
{
    return px_text(x + (w - px_text_w(f, s)) / 2, y, f, s, c);
}

/* a label on a solid block (the last-turned knob, a tag): one dot of margin round the text */
static int32_t px_tag(int32_t x, int32_t y, uint32_t f, const char *s, uint16_t fill, uint16_t ink)
{
    int32_t w = px_text_w(f, s) + 2;
    px_box(x, y, w, f == PXF_3 ? 7 : 9, fill);
    px_text(x + 1, y + 1, f, s, ink);
    return w;
}

/* a small drawing from rows of '#' and '.', at (x, y) */
static void px_art(int32_t x, int32_t y, const char *const *art, int32_t rows, uint16_t c)
{
    int32_t r, i;
    for (r = 0; r < rows; r++)
        for (i = 0; art[r][i]; i++)
            if (art[r][i] == '#')
                px_dot(x + i, y + r, c);
}

/* s in the 5 x 7 face with every dot an n x n block (the UPDATE MODE count) */
static void px_text_big(int32_t x, int32_t y, int32_t n, const char *s, uint16_t c)
{
    for (; *s; s++, x += 6 * n) {
        uint32_t g = px_glyph(*s), r, b;
        for (r = 0; r < 7u; r++)
            for (b = 0; b < 5u; b++)
                if (PX5[g][r] >> (4u - b) & 1u)
                    px_box(x + (int32_t)b * n, y + (int32_t)r * n, n, n, c);
    }
}

/* SPEED (-200..200 %) as chevrons centred on (cx, cy): one per 50 %, pointing the way the tape plays; stopped, a
 * pause sign */
static void px_chevrons(int32_t cx, int32_t cy, int32_t v, uint16_t c)
{
    int32_t n = v < 0 ? -v : v, k, s = v < 0 ? -1 : 1;
    n = n == 0 ? 0 : clamp(n / 50 + 1, 1, 4);
    if (!n) {
        px_box(cx - 4, cy - 5, 3, 11, c);
        px_box(cx + 2, cy - 5, 3, 11, c);
    }
    for (k = 0; k < n; k++) {
        int32_t x0 = cx - n * 5 / 2 + k * 5 + (s < 0 ? 4 : 0);
        px_line(x0, cy - 5, x0 + 4 * s, cy, c, 1);
        px_line(x0 + 4 * s, cy, x0, cy + 5, c, 1);
        px_line(x0 + s, cy - 5, x0 + 5 * s, cy, c, 1);
        px_line(x0 + 5 * s, cy, x0 + s, cy + 5, c, 1);
    }
}

/* ---------------------------------------------------------- pictograms --- */
enum {
    PK_KNOB, PK_FADER, PK_ATTACK, PK_DECAY, PK_SUSTAIN, PK_RELEASE, PK_START, PK_LENGTH, PK_SPEED, PK_LAYERS,
    PK_SQUARE, PK_DOTS, PK_BOWTIE, PK_LOOP, PK_MIX, PK_DRIVE, PK_STAIRS, PK_NOISE, PK_TONE, PK_CLOCK, PK_ROOM,
    PK_SHAPE, PK_FOLD, PK_SKEW, PK_SMOOTH, PK_STEPS, PK_SLEW, PK_SWING, PK_KEYS, PK_SHELF_LO, PK_SHELF_HI, PK_FILTER,
    PK_PAN, PK_TOGGLE, PK_FADE, PK_WINDOW, PK_GATE, PK_PRE, PK_MODE, PK_DIR, PK_STEPAT, PK_NONE,
    PK_CURVE, PK_VAR, PK_SRC, PK_OSC, PK_DETUNE, PK_CUTOFF, PK_RES, PK_ENVAMT, PK_KTRK, PK_VOICES, PK_PATTERN,
    PK_SCALE, PK_SLOPE, PK_CMOD, PK_SCAN
};

/* the waveform shapes WAVE's SHAPE picks, at phase p (0..63 a cycle), x1000 */
static int32_t px_wave(uint32_t shape, int32_t p)
{
    p &= 63;
    if (shape == 1u)                                     /* triangle */
        return p < 16 ? p * 1000 / 16 : p < 48 ? (32 - p) * 1000 / 16 : (p - 64) * 1000 / 16;
    if (shape == 2u)                                     /* square */
        return p < 32 ? 1000 : -1000;
    if (shape == 3u)                                     /* saw: up, then the drop */
        return (p - 32) * 1000 / 32;
    if (shape == 4u) {                                   /* random: 8 held steps a cycle */
        static const int16_t RS[8] = {600, -300, 900, -800, 100, 700, -500, -100};
        return RS[(p / 8) & 7];
    }
    return px_sin(p);
}

/* a soft clip with gain g (x1000) that still maps 1000 to 1000: x g / (1 + |x g|), scaled back */
static int32_t px_clip(int32_t x, int32_t g)
{
    int32_t k = x * g / 1000, a = k < 0 ? -k : k;
    return k * (1000 + g) / (1000 + a) * 1000 / g;
}

/* The channel strip's response at x of w dots (8 octaves, 40 Hz to 10 kHz, left to right), in tenths of a dB: LOW and
 * HIGH shelves (+-12 dB, half of it at 30 % and 70 % of the width, 210 Hz and 1.9 kHz, the slope two octaves wide, as
 * mixer.c's first-order shelves), FILT's low-pass (left of 0: its corner moves left from
 * the top end) or high-pass (right of 0: from the bottom end), 12 dB an octave past the corner. A shelf of only
 * LOW or HIGH is what PK_SHELF_* draw, with the other values left at 0. */
static int32_t ch_resp(const int16_t *ch, int32_t x, int32_t w)
{
    int32_t lo = clamp((w * 30 / 100 - x) * 1000 / (w * 25 / 100 + 1) + 500, 0, 1000);   /* 1000 under the shelf */
    int32_t hi = clamp((x - w * 70 / 100) * 1000 / (w * 25 / 100 + 1) + 500, 0, 1000);
    int32_t db = ch[CH_LOW] * lo / 100 + ch[CH_HIGH] * hi / 100, f = ch[CH_FILT], c;
    if (f < 0) {
        c = w - (-f) * w * 85 / 10000;                   /* the low-pass corner, from the top down to 15 % */
        if (x > c)
            db -= (x - c) * 960 / w;                     /* 12 dB / octave, an octave being w / 8 dots */
    } else if (f > 0) {
        c = f * w * 85 / 10000;
        if (x < c)
            db -= (c - x) * 960 / w;
    }
    return db;
}

/* a fader that is also a meter: the frame, the live level rising inside it (m of 19 dots), and the level set
 * with the knob as two notches either side, pointing in (they move; the fill moves on its own) */
static void px_meter_fader(int32_t x, int32_t y, int32_t ratio, int32_t m, uint16_t c)
{
    int32_t i, ly = y + 20 - ratio * 19 / 1000;
    px_frame(x + 8, y, 6, 21, c, 1);
    for (i = 1; i < 20; i += 3) {
        px_dot(x + 4, y + i, px_dim);
        px_dot(x + 17, y + i, px_dim);
    }
    if (m > 0)
        px_box(x + 10, y + 20 - m, 2, m, c);
    for (i = 0; i < 3; i++) {                            /* the notches: little arrowheads, 3 dots deep */
        px_line(x + 5 + i, ly - (2 - i), x + 5 + i, ly + (2 - i), c, 1);
        px_line(x + 16 - i, ly - (2 - i), x + 16 - i, ly + (2 - i), c, 1);
    }
}

/* 0..w on a log scale (-48 dB .. 0 dBFS) of a peak word (the ISR's track meters) */
static int32_t meter_w(int32_t peak, int32_t w)
{
    int32_t lg = 0, v;
    if (peak < 128)
        return 0;
    while ((peak >> lg) > 1)
        lg++;
    v = lg * 8 + (((peak << 3) >> lg) & 7);
    return clamp((v - 56) * w / 64, 0, w);
}

static void px_picto(uint32_t kind, int32_t x, int32_t y, const pdesc_t *d, int32_t v, uint16_t c)
{
    int32_t r = param_ratio(d, v), i, cx = x + 11, cy = y + 10, b = y + 20;
    uint16_t m = px_dim;
    if (kind == PK_DRIVE || kind == PK_STAIRS || kind == PK_NOISE || kind == PK_TONE)
        px_frame(x, y, 22, 21, m, 2);                    /* a graph: its dotted box */
    switch (kind) {
    case PK_KNOB:                                        /* a dotted dial with a pointer (bipolar: - and + under) */
    default: {
        int32_t a = d->min < 0 ? v * 24 / (v < 0 ? -d->min : d->max) : -24 + r * 48 / 1000;
        px_ring(cx, cy, 9, c, 2);
        px_line(cx, cy, px_px(cx, 7, a), px_py(cy, 7, a), c, 1);
        px_box(cx - 1, cy - 1, 2, 2, c);
        if (d->min < 0) {
            px_line(x, b, x + 2, b, c, 1);
            px_line(x + 19, b, x + 21, b, c, 1);
            px_line(x + 20, b - 1, x + 20, b + 1, c, 1);
        }
        break;
    }
    case PK_FADER: {                                     /* a fader with ticks either side; bipolar from the middle */
        int32_t h;
        px_frame(x + 8, y, 6, 21, c, 1);
        for (i = 1; i < 20; i += 3) {
            px_line(x + 4, y + i, x + 5, y + i, m, 1);
            px_line(x + 16, y + i, x + 17, y + i, m, 1);
        }
        if (d->min < 0) {
            h = v * 9 / (v < 0 ? -d->min : d->max);
            px_box(x + 10, h > 0 ? y + 10 - h : y + 10, 2, (h < 0 ? -h : h) + 1, c);
        } else {
            h = r * 19 / 1000;
            px_box(x + 10, y + 20 - h, 2, h, c);
        }
        break;
    }
    case PK_ATTACK: {                                    /* the rise: longer as the value grows */
        int32_t w = 1 + r * 17 / 1000;
        px_line(x, b, x + w, y + 1, c, 1);
        px_line(x + w, y + 1, x + 21, y + 1, c, 1);
        px_line(x, b, x + 21, b, m, 2);
        break;
    }
    case PK_DECAY:                                       /* a hit and its fall (DEC, DECAY, DAMP) */
    case PK_RELEASE: {
        int32_t w = 1 + r * 17 / 1000, t = kind == PK_RELEASE ? y + 7 : y + 1, x0 = kind == PK_RELEASE ? x + 3 : x;
        if (kind == PK_RELEASE)
            px_line(x, t, x0, t, c, 2);                  /* from the sustain level, dotted */
        else
            px_line(x, b, x, t, c, 1);
        px_line(x0, t, x0 + w, b, c, 1);
        px_line(x0 + w, b, x + 21, b, c, 1);
        break;
    }
    case PK_SUSTAIN: {                                   /* a held level */
        int32_t l = b - r * 19 / 1000;
        px_line(x, b, x + 4, l, c, 1);
        px_line(x + 4, l, x + 17, l, c, 1);
        px_line(x + 17, l, x + 21, b, c, 1);
        px_line(x + 4, l, x + 4, b, m, 2);
        px_line(x + 17, l, x + 17, b, m, 2);
        break;
    }
    case PK_START:                                       /* the tape and where the loop starts on it */
    case PK_LENGTH: {
        int32_t p = x + 1 + r * 19 / 1000;
        px_frame(x, y + 5, 22, 11, c, 1);
        for (i = x + 2; i < x + 21; i += 3) {
            px_dot(i, y + 7, m);
            px_dot(i, y + 13, m);
        }
        if (kind == PK_START) {
            px_box(p, y + 2, 2, 17, c);
            px_line(p - 2, y, p + 3, y, c, 1);
            px_line(p - 1, y + 1, p + 2, y + 1, c, 1);
        } else {
            px_box(x + 2, y + 9, p - x - 1, 3, c);
            px_line(x + 1, y + 2, x + 1, y + 18, c, 1);
            px_line(p + 1, y + 2, p + 1, y + 18, c, 1);
        }
        break;
    }
    case PK_SPEED:                                       /* chevrons: one per 50 %, their way the direction */
        px_chevrons(cx, cy, v, c);
        px_line(x, b, x + 2, b, c, 1);
        px_line(x + 19, b, x + 21, b, c, 1);
        px_line(x + 20, b - 1, x + 20, b + 1, c, 1);
        break;
    case PK_LAYERS: {                                    /* DUB: the old take (two layers) under the new one (top), */
        int32_t k, keep = v >= 0 ? 100 : 100 + v;       /* solid while that part is kept (dotted: faded out) */
        for (k = 0; k < 3; k++) {
            int32_t yy = y + 15 - k * 6;
            if (k < 2 ? keep > k * 50 : v < 100)
                px_box(x + 2 + k * 2, yy, 18 - k * 4, 4, c);
            else
                px_frame(x + 2 + k * 2, yy, 18 - k * 4, 4, m, 2);
        }
        break;
    }
    case PK_SQUARE: {                                    /* a grain's size: a solid block in its largest outline */
        int32_t s = 2 + r * 18 / 1000;
        px_frame(x + 1, y, 20, 20, m, 2);
        px_box(x + 1, y + 20 - s, s, s, c);
        break;
    }
    case PK_DOTS: {                                      /* density: of 25 places, 1..25 lit */
        int32_t n = 1 + r * 24 / 1000, k;
        for (k = 0; k < 25; k++) {
            int32_t gx = x + 2 + (k % 5) * 4, gy = y + 1 + (k / 5) * 4;
            /* lit in a scattered order, so a low density reads as a few grains, not one corner */
            if ((k * 7) % 25 < n)
                px_box(gx, gy, 2, 2, c);
            else
                px_dot(gx, gy, m);
        }
        break;
    }
    case PK_BOWTIE: {                                    /* stereo spread: the wings open with the value */
        int32_t h = 1 + r * 8 / 1000;
        px_box(cx - 1, cy - 4, 2, 9, c);
        px_line(cx - 3, cy, x + 1, cy - h, c, 1);
        px_line(cx - 3, cy, x + 1, cy + h, c, 1);
        px_line(x + 1, cy - h, x + 1, cy + h, c, 1);
        px_line(cx + 2, cy, x + 20, cy - h, c, 1);
        px_line(cx + 2, cy, x + 20, cy + h, c, 1);
        px_line(x + 20, cy - h, x + 20, cy + h, c, 1);
        break;
    }
    case PK_LOOP: {                                      /* feedback: the dial's ring turns to chaos as it rises */
        /* Each of the ring's 64 points moves off radius 8 by up to 2.2 dots, so it never leaves the box: a slow
         * wobble at low feedback (two sines), giving way to jitter near the top, the way a loop near self-
         * oscillation smears. Fixed seeds: the same value draws the same ring. The pointer reads the value. */
        int32_t k, px0 = 0, py0 = 0, fx = 0, fy = 0, amp = r * 22 / 1000;   /* amp: tenths of a dot */
        uint32_t s = 2463534242u;
        for (k = 0; k <= 64; k++) {
            int32_t ak = k & 63, smooth = (px_sin(ak * 5 + 7) * 6 + px_sin(ak * 11 + 3) * 4) / 10, jit, d, rad, xx, yy;
            s ^= s << 13;
            s ^= s >> 17;
            s ^= s << 5;
            jit = (int32_t)(s % 2001u) - 1000;
            d = k == 64 ? 0 : (smooth * (1000 - r) + jit * r) / 1000;       /* -1000..1000 */
            rad = 80 + (k == 64 ? 0 : d * amp / 1000);                    /* tenths of a dot */
            xx = cx + (px_sin(ak) * rad + (px_sin(ak) >= 0 ? 5000 : -5000)) / 10000;
            yy = cy - (px_cos(ak) * rad + (px_cos(ak) >= 0 ? 5000 : -5000)) / 10000;
            if (k == 64) {                                                /* close on the first point */
                xx = fx;
                yy = fy;
            }
            if (k)
                px_line(px0, py0, xx, yy, c, 1);
            else
                fx = xx, fy = yy;
            px0 = xx;
            py0 = yy;
        }
        k = -24 + r * 48 / 1000;
        px_line(cx, cy, px_px(cx, 5, k), px_py(cy, 5, k), c, 1);
        px_box(cx - 1, cy - 1, 2, 2, c);
        break;
    }
    case PK_MIX: {                                       /* dry against wet: two bars */
        int32_t hw = r * 19 / 1000, hd = 19 - hw;
        px_frame(x + 4, y, 5, 21, m, 1);
        px_frame(x + 13, y, 5, 21, m, 1);
        px_box(x + 5, b - hd, 3, hd, c);
        px_box(x + 14, b - hw, 3, hw, c);
        px_dot(x + 6, b + 1, c);                         /* (the dry side's foot: the left bar is dry) */
        break;
    }
    case PK_DRIVE: {                                     /* the transfer curve, steeper with drive */
        int32_t g = 1000 + r * 7, px0 = 0, py0 = 0;
        px_line(x, cy, x + 21, cy, m, 2);
        px_line(cx, y, cx, b, m, 2);
        for (i = 0; i <= 20; i++) {
            int32_t in = (i - 10) * 100, o = px_clip(in, g), yy = cy - o * 9 / 1000;
            if (i)
                px_line(px0, py0, x + i, yy, c, 1);
            px0 = x + i;
            py0 = yy;
        }
        break;
    }
    case PK_STAIRS: {                                    /* crush: fewer, bigger steps */
        int32_t n = 8 - r * 6 / 1000, k, w = 20 / n, h = 19 / n;
        for (k = 0; k < n; k++) {
            px_line(x + 1 + k * w, b - k * h, x + 1 + (k + 1) * w, b - k * h, c, 1);
            px_line(x + 1 + (k + 1) * w, b - k * h, x + 1 + (k + 1) * w, b - (k + 1) * h, c, 1);
        }
        break;
    }
    case PK_NOISE: {                                     /* scattered dots, as many as the value */
        uint32_t s = 7u;
        int32_t n = 3 + r * 57 / 1000, k;
        for (k = 0; k < n; k++) {
            s = s * 1664525u + 1013904223u;
            px_dot(x + 1 + (int32_t)((s >> 16) % 20u), y + (int32_t)((s >> 8) % 21u), c);
        }
        break;
    }
    case PK_TONE: {                                      /* a tilt: dark leans the top down, bright the bottom up */
        int32_t l = y + 3 + (r > 500 ? (r - 500) * 14 / 500 : 0), h = y + 3 + (r < 500 ? (500 - r) * 14 / 500 : 0);
        px_line(x, l, x + 6, l, c, 1);
        px_line(x + 6, l, x + 15, h, c, 1);
        px_line(x + 15, h, x + 21, h, c, 1);
        px_line(x, b, x + 21, b, m, 2);
        break;
    }
    case PK_CLOCK: {                                     /* time: a clock hand, a full turn over the range */
        int32_t a = r * 63 / 1000, k;
        px_ring(cx, cy, 9, c, 2);
        for (k = 0; k < 64; k += 16)
            px_dot(px_px(cx, 7, k), px_py(cy, 7, k), c);
        px_line(cx, cy, cx, cy - 4, m, 1);
        px_line(cx, cy, px_px(cx, 6, a), px_py(cy, 6, a), c, 1);
        px_box(cx - 1, cy - 1, 2, 2, c);
        break;
    }
    case PK_ROOM: {                                      /* size: sound spreading from a source, arcs out to the */
        int32_t n = 1 + r * 3 / 1000, k, ax = x + 3, a;  /* room's walls; as many lit as SIZE reaches (1..4) */
        px_box(ax - 1, cy - 1, 3, 3, c);
        for (k = 0; k < 4; k++) {
            int32_t rad = 5 + k * 4;
            for (a = 1; a < 32; a += k < n ? 1 : 2) {    /* the right half; the unlit ones dotted */
                int32_t px = px_px(ax, rad, a), py = px_py(cy, rad, a);
                if (px <= x + 21 && py >= cy - 9 && py <= cy + 9)
                    px_dot(px, py, k < n ? c : m);
            }
        }
        break;
    }
    case PK_SHAPE:                                       /* one cycle of the shape */
    case PK_OSC:                                         /* SYNTH's wave: SIN TRI SQR SAW, PLS a 25 % pulse */
    case PK_FOLD:
    case PK_SKEW: {
        int32_t px0 = 0, py0 = 0;
        px_line(x, cy, x + 21, cy, m, 2);
        for (i = 0; i <= 21; i++) {
            int32_t p = i * 64 / 22, o, yy;
            if (kind == PK_OSC && v == 4) {
                o = (p & 63) < 16 ? 1000 : -1000;
            } else if (kind == PK_SHAPE || kind == PK_OSC) {
                o = px_wave((uint32_t)v, p);
            } else if (kind == PK_FOLD) {                /* the sine driven past the rails folds back */
                o = px_sin(p) * (1000 + r * 3) / 1000;
                while (o > 1000 || o < -1000)
                    o = o > 1000 ? 2000 - o : -2000 - o;
            } else {                                     /* a triangle, its peak moved by SKEW */
                int32_t pk = 32 + v * 30 / 100, q = p * 2 > 64 ? p * 2 - 64 : p * 2;   /* two cycles */
                o = q < pk ? -1000 + q * 2000 / (pk ? pk : 1) : 1000 - (q - pk) * 2000 / (64 - pk ? 64 - pk : 1);
            }
            yy = cy - o * 8 / 1000;
            if (i)
                px_line(px0, py0, x + i, yy, c, 1);
            px0 = x + i;
            py0 = yy;
        }
        break;
    }
    case PK_SMOOTH:                                      /* steps whose edges lean as smoothing rises */
    case PK_SLEW: {
        static const int8_t LV[2][5] = {{12, 3, 16, 7, 12}, {18, 2, 18, 2, 18}};
        const int8_t *lv = LV[kind == PK_SLEW];
        int32_t s = r * 4 / 1000, k;
        for (k = 0; k < 4; k++) {
            int32_t x0 = x + k * 5 + (k ? s : 0), x1 = x + (k + 1) * 5;
            px_line(x0, y + lv[k], x1, y + lv[k], c, 1);
            px_line(x1, y + lv[k], x1 + s, y + lv[k + 1], c, 1);
        }
        px_line(x + 20 + s, y + lv[4], x + 21, y + lv[4], c, 1);
        break;
    }
    case PK_STEPS: {                                     /* of 16 steps, v lit */
        int32_t k;
        for (k = 0; k < 16; k++) {
            int32_t gx = x + 3 + (k % 4) * 5, gy = y + 2 + (k / 4) * 5;
            if (k < v)
                px_box(gx, gy, 3, 3, c);
            else
                px_dot(gx + 1, gy + 1, m);
        }
        break;
    }
    case PK_SWING: {                                     /* beats fixed, the off-beats pushed late */
        int32_t s = r * 3 / 1000, k;
        for (k = 0; k < 2; k++) {
            int32_t xb = x + 1 + k * 11;
            px_box(xb, y + 4, 2, 15, c);
            px_box(xb + 5 + s, y + 9, 2, 10, c);
        }
        px_line(x, b + 1, x + 21, b + 1, m, 2);
        break;
    }
    case PK_SHELF_LO:                                    /* a shelf: that end lifted or cut */
    case PK_SHELF_HI:
    case PK_FILTER: {                                    /* the filter: low-pass left of 0, high-pass right */
        int16_t ch[NCH] = {0, 0, 0, 0};
        int32_t py = 0;
        ch[kind == PK_SHELF_LO ? CH_LOW : kind == PK_SHELF_HI ? CH_HIGH : CH_FILT] = (int16_t)v;
        px_line(x, cy, x + 21, cy, m, 2);
        for (i = 0; i <= 21; i++) {
            int32_t yy = clamp(cy - ch_resp(ch, i, 22) * 8 / 120, y, b);
            if (i)
                px_line(x + i - 1, py, x + i, yy, c, 1);
            py = yy;
        }
        break;
    }
    case PK_PAN: {                                       /* the place between the speakers */
        int32_t p = x + 11 + v * 9 / 100;
        px_text(x, y + 1, PXF_3, "L", c);
        px_text(x + 19, y + 1, PXF_3, "R", c);
        px_line(x + 1, cy + 3, x + 20, cy + 3, m, 2);
        px_line(x + 11, cy + 1, x + 11, cy + 5, m, 1);
        px_box(p - 1, cy + 1, 3, 5, c);
        break;
    }
    case PK_TOGGLE: {                                    /* a switch: the block left (off, FREE) or right (on) */
        int32_t on = v > d->min;
        px_frame(x + 1, cy - 4, 20, 9, c, 1);
        if (on)
            px_box(x + 11, cy - 2, 8, 5, c);
        else
            px_frame(x + 3, cy - 2, 8, 5, c, 1);
        break;
    }
    case PK_FADE: {                                      /* a crossfade: two ramps crossing, as wide as the fade */
        int32_t w = 2 + r * 18 / 1000, x0 = cx - w / 2, x1 = x0 + w;
        px_line(x, y + 3, x0, y + 3, c, 1);
        px_line(x0, y + 3, x1, b, c, 1);
        px_line(x0, b, x1, y + 3, c, 1);
        px_line(x1, y + 3, x + 21, y + 3, m, 2);
        px_line(x, b, x0, b, m, 2);
        break;
    }
    case PK_WINDOW: {                                    /* a grain's window: square at 0, a smooth hump at 100 */
        int32_t py = 0;
        px_line(x, b, x + 21, b, m, 2);
        for (i = 0; i <= 21; i++) {
            int32_t hump = px_sin(i * 32 / 21) * 18 / 1000, yy = b - (18 * (1000 - r) + hump * r) / 1000;
            if (i == 0 || i == 21)
                yy = b - (r > 950 ? 0 : 18 * (1000 - r) / 1000);
            if (i)
                px_line(x + i - 1, py, x + i, yy, c, 1);
            py = yy;
        }
        break;
    }
    case PK_GATE: {                                      /* a hit's envelope and the threshold over it */
        int32_t t = b - r * 19 / 1000;
        px_line(x + 1, b, x + 3, y + 1, c, 1);
        px_line(x + 3, y + 1, x + 21, b, c, 1);
        px_line(x, t, x + 21, t, c, 2);
        break;
    }
    case PK_PRE: {                                       /* pre-delay: the dry hit, a gap, the tail */
        int32_t g = x + 3 + r * 12 / 1000;
        px_line(x + 1, b, x + 1, y + 1, c, 1);
        px_line(x + 2, b, g, b, m, 2);
        px_line(g, b, g + 2, y + 8, c, 1);
        px_line(g + 2, y + 8, x + 21, b, c, 1);
        break;
    }
    case PK_MODE:                                        /* KEYS: a key pressed; FLLW: an envelope over a wave */
        if (v == d->min) {
            px_frame(x + 6, y + 1, 10, 19, c, 1);
            px_box(x + 8, y + 12, 6, 6, c);
            px_line(x + 11, y - 1, x + 11, y + 4, c, 1);
        } else {
            for (i = 0; i <= 21; i++)
                px_dot(x + i, cy + px_sin(i * 9) * (8 - i * 7 / 21) / 1000, m);
            px_line(x, cy - 8, x + 21, cy - 1, c, 1);
            px_line(x, cy + 8, x + 21, cy + 1, c, 1);
        }
        break;
    case PK_DIR: {                                       /* FWD, REV, PING (both ways), RND (scattered steps) */
        int32_t k;
        if (v == 3) {
            static const int8_t RY[5] = {3, 14, 7, 17, 10};
            for (k = 0; k < 5; k++)
                px_box(x + 1 + k * 4, y + RY[k], 3, 3, c);
            break;
        }
        px_line(x + 2, cy, x + 19, cy, c, 1);
        if (v == 0 || v == 2) {
            px_line(x + 19, cy, x + 15, cy - 4, c, 1);
            px_line(x + 19, cy, x + 15, cy + 4, c, 1);
        }
        if (v == 1 || v == 2) {
            px_line(x + 2, cy, x + 6, cy - 4, c, 1);
            px_line(x + 2, cy, x + 6, cy + 4, c, 1);
        }
        break;
    }
    case PK_SCAN:                                        /* GRAIN's SCAN: what grains read, and where */
        if (v == 0) {                                    /* TAPE: the tape's two reels */
            px_ring(x + 6, cy, 5, c, 1);
            px_ring(x + 16, cy, 5, c, 1);
            px_line(x + 6, cy + 5, x + 16, cy + 5, c, 1);
            break;
        }
        px_frame(x, y + 5, 22, 11, m, 2);                /* the buffer */
        if (v == 1) {                                    /* STR: stretched, an arrow both ways across it */
            px_line(x + 3, cy, x + 18, cy, c, 1);
            px_line(x + 3, cy, x + 6, cy - 3, c, 1);
            px_line(x + 3, cy, x + 6, cy + 3, c, 1);
            px_line(x + 18, cy, x + 15, cy - 3, c, 1);
            px_line(x + 18, cy, x + 15, cy + 3, c, 1);
        } else if (v == 2) {                             /* POS: a pin at a spot */
            px_line(x + 8, y + 3, x + 8, y + 17, c, 1);
            px_box(x + 6, y + 1, 5, 4, c);
        } else {                                         /* DLY: the write head, and the read point trailing it */
            px_line(x + 18, y + 3, x + 18, y + 17, c, 1);
            px_line(x + 6, y + 5, x + 6, y + 15, c, 2);
            px_line(x + 7, cy, x + 16, cy, c, 1);
            px_line(x + 7, cy, x + 10, cy - 3, c, 1);
            px_line(x + 7, cy, x + 10, cy + 3, c, 1);
        }
        break;
    case PK_STEPAT: {                                    /* 16 steps, the one it starts on solid */
        int32_t k;
        for (k = 0; k < 16; k++) {
            int32_t gx = x + 3 + (k % 4) * 5, gy = y + 2 + (k / 4) * 5;
            if (k + 1 == v)
                px_box(gx, gy, 3, 3, c);
            else
                px_dot(gx + 1, gy + 1, m);
        }
        break;
    }
    case PK_CURVE: {                                     /* a rise bent by the value: - bows up (log), + sags (exp) */
        int32_t py = b;
        px_line(x, b, x + 21, y + 1, m, 3);
        for (i = 1; i <= 21; i++) {
            int32_t t = i * 1000 / 21, bend = v * t / 1000 * (1000 - t) / 100;   /* -1000..1000 x t(1-t) */
            int32_t yy = b - (t - bend) * (b - y - 1) / 1000;
            px_line(x + i - 1, py, x + i, clamp(yy, y, b), c, 1);
            py = clamp(yy, y, b);
        }
        break;
    }
    case PK_VAR: {                                       /* variation: a loop of steps, and the next time round dotted, */
        static const int8_t LV[5] = {12, 4, 16, 8, 13};  /* further off as the value grows */
        int32_t k, dv = r * 6 / 1000;
        for (k = 0; k < 5; k++) {
            int32_t x0 = x + k * 4 + 1, alt = ((k * 3 + 1) % 3 - 1) * dv;
            px_line(x0, y + LV[k], x0 + 3, y + LV[k], c, 1);
            if (dv)
                px_line(x0, clamp(y + LV[k] + alt, y, b), x0 + 3, clamp(y + LV[k] + alt, y, b), c, 2);
        }
        break;
    }
    case PK_SRC: {                                       /* the source: a jack and its name */
        const char *n = d->names[v - d->min];
        px_frame(x + 1, y + 2, 20, 13, c, 1);
        px_text_c(x + 1, 20, y + 6, PXF_3, n, c);
        px_line(x + 11, y + 15, x + 11, b, c, 1);
        px_box(x + 9, b - 1, 5, 2, c);
        break;
    }
    case PK_NONE:
        break;
    case PK_PATTERN: {                                   /* when grains fire: EVEN, SWNG (late off-beats), CLST, RND */
        static const int8_t AT[4][6] = {{0, 4, 8, 12, 16, 20}, {0, 6, 8, 14, 16, 20}, {0, 2, 4, 12, 14, 16},
                                        {1, 3, 9, 10, 15, 20}};
        int32_t k;
        px_line(x, b, x + 21, b, m, 2);
        for (k = 0; k < 6; k++)
            px_box(x + AT[v & 3][k], y + 6, 2, 9, c);
        break;
    }
    case PK_SCALE: {                                     /* 12 semitones round a ring, the scale's lit (OFF / HARM: */
        static const uint16_t SC[5] = {0, 0xFFF, 0xAB5, 0x5AD, 0x295};   /* none / the harmonics' 1 5 3) */
        uint32_t set = d->names == N_RSCAL ? (v ? SC[v + 1] : 0x091u) : SC[v % 5];
        int32_t k;
        for (k = 0; k < 12; k++) {
            int32_t a = k * 64 / 12, xx = px_px(cx, 8, a), yy = px_py(cy, 8, a);
            if ((set >> k) & 1u)
                px_box(xx - 1, yy - 1, 3, 3, c);
            else
                px_dot(xx, yy, m);
        }
        break;
    }
    case PK_SLOPE: {                                     /* the filter's shape: low-pass, band-pass, high-pass */
        static const int8_t LV[3][8] = {{4, 4, 4, 4, 6, 11, 16, 19}, {19, 14, 7, 4, 4, 7, 14, 19},
                                        {19, 16, 11, 6, 4, 4, 4, 4}};
        int32_t k;
        px_line(x, b, x + 21, b, m, 2);
        for (k = 1; k < 8; k++)
            px_line(x + (k - 1) * 3, y + LV[v % 3][k - 1], x + k * 3, y + LV[v % 3][k], c, 1);
        break;
    }
    case PK_CMOD: {                                      /* what CRUSH takes: the bits (tall steps), the rate (wide */
        int32_t k, w = v == 0 ? 2 : 5, h = v == 1 ? 2 : 5;   /* steps), or both */
        px_frame(x, y, 22, 21, m, 2);
        for (k = 0; k * w < 18 && k * h < 16; k++) {
            px_line(x + 2 + k * w, b - 2 - k * h, x + 2 + (k + 1) * w, b - 2 - k * h, c, 1);
            px_line(x + 2 + (k + 1) * w, b - 2 - k * h, x + 2 + (k + 1) * w, b - 2 - (k + 1) * h, c, 1);
        }
        break;
    }
    case PK_DETUNE: {                                    /* two saws, the second (dotted) drifting ahead with DTUN */
        int32_t sh = r * 5 / 1000, k;
        for (k = 0; k < 2; k++) {
            int32_t x0 = x + k * 11;
            px_line(x0, y + 16, x0 + 10, y + 4, c, 1);
            px_line(x0 + 10, y + 4, x0 + 10, y + 16, c, 1);
            if (x0 + 10 + sh <= x + 21) {
                px_line(x0 + sh, y + 18, x0 + 10 + sh, y + 6, m, 2);
                px_line(x0 + 10 + sh, y + 6, x0 + 10 + sh, y + 18, m, 2);
            }
        }
        break;
    }
    case PK_CUTOFF:                                      /* a low-pass: flat, then falling past the cutoff */
    case PK_RES: {                                       /* the same filter, its peak as tall as the resonance */
        int32_t kx = kind == PK_CUTOFF ? 2 + r * 17 / 1000 : 12, pk = kind == PK_RES ? r * 9 / 1000 : 2, py = 0;
        px_line(x, y + 8, x + 21, y + 8, m, 2);
        for (i = 0; i <= 21; i++) {
            int32_t d = i - kx, yy = y + 8 - pk * 9 / (9 + d * d * 3) + (d > 0 ? d * 2 : 0);
            yy = clamp(yy, y, b);
            if (i)
                px_line(x + i - 1, py, x + i, yy, c, 1);
            py = yy;
        }
        break;
    }
    case PK_ENVAMT: {                                    /* the envelope's push on the cutoff: up, or down below 0 */
        int32_t h = v * 9 / 100, xs[4] = {x, x + 5, x + 12, x + 21}, ys[4] = {cy, cy - h, cy - h / 2, cy};
        px_line(x, cy, x + 21, cy, m, 2);
        for (i = 1; i < 4; i++)
            px_line(xs[i - 1], ys[i - 1], xs[i], ys[i], c, 1);
        break;
    }
    case PK_KTRK: {                                      /* key tracking: across the keys, the cutoff climbs */
        int32_t k = r * 8 / 1000;
        for (i = 0; i < 22; i += 3)
            px_line(x + i, b - 1, x + i, b, m, 1);
        px_line(x, cy, x + 21, cy, m, 2);
        px_line(x, cy + k, x + 21, cy - k, c, 1);
        break;
    }
    case PK_VOICES: {                                    /* the voices stacked: as many solid as play at once */
        int32_t gap = d->max > 3 ? 5 : 7, h = d->max > 3 ? 3 : 4;
        for (i = 0; i < d->max; i++)
            if (i < v)
                px_box(x + 2, y + 2 + i * gap, 18, h, c);
            else
                px_frame(x + 2, y + 2 + i * gap, 18, h, m, 2);
        break;
    }
    case PK_KEYS: {                                      /* an octave: one outline, the dividers, the root marked */
        /* 7 white keys of 3 dots in one frame, black keys as solid blocks over the dividers; the root is a solid
         * foot on its white key, or a black key drawn hollow. Fewer strokes than a key-by-key drawing, so it reads
         * at this size. */
        static const int8_t WHITE[12] = {0, -1, 1, -1, 2, 3, -1, 4, -1, 5, -1, 6};
        static const int8_t BLACK_X[12] = {-1, 3, -1, 6, -1, -1, 12, -1, 15, -1, 18, -1};   /* the block's x */
        int32_t n = (int32_t)((uint32_t)v % 12u), k;
        px_frame(x, y + 3, 22, 16, c, 1);
        for (k = 1; k < 7; k++)
            px_line(x + k * 3, y + 12, x + k * 3, y + 17, c, 1);
        for (k = 0; k < 12; k++)
            if (BLACK_X[k] >= 0) {
                if (k == n)                              /* the root, black: hollow, a dot under it */
                    px_frame(x + BLACK_X[k] - 1, y + 3, 3, 9, c, 1);
                else
                    px_box(x + BLACK_X[k] - 1, y + 3, 2, 8, c);
            }
        if (WHITE[n] >= 0)                               /* the root, white: the key filled under the black ones */
            px_box(x + WHITE[n] * 3 + 1, y + 12, 2, 6, c);
        break;
    }
    }
}

/* the pictogram of each knob of each page (page 2 after page 1) */
static const uint8_t DEV_PK[NDEV][NPK] = {
    {PK_START, PK_LENGTH, PK_SPEED, PK_LAYERS,       /* TAPE: STRT LEN SPD DUB */
     PK_FADE, PK_TOGGLE, PK_TOGGLE, PK_FADER,        /*       XFAD REV HALF GAIN */
     PK_SRC, PK_CLOCK, PK_FADER, PK_NONE},           /*       REEL ROTA LVL */
    {PK_SQUARE, PK_DOTS, PK_KNOB, PK_BOWTIE,         /* GRAIN: SIZE RATE PTCH SPRD */
     PK_MIX, PK_NOISE, PK_WINDOW, PK_DOTS,           /*        WET SPRY CONT REV */
     PK_PATTERN, PK_SCALE, PK_VAR, PK_NONE,          /*        PATN SCAL PRND */
     PK_SCAN, PK_SPEED, PK_START, PK_LOOP},          /*        SCAN WARP OFST FDBK */
    {PK_KEYS, PK_DECAY, PK_TONE, PK_MIX,             /* RESONATOR: PTCH DEC TONE WET */
     PK_CUTOFF, PK_RES, PK_SLOPE, PK_SCALE},         /*            CUT RES SLOP SCAL */
    {PK_DRIVE, PK_STAIRS, PK_NOISE, PK_TONE,         /* COLOR: DRIV CRSH NOIS TILT */
     PK_DECAY, PK_TONE, PK_CMOD, PK_MIX,             /*        NDEC NTON CMOD WET */
     PK_FADER, PK_NONE, PK_NONE, PK_NONE},           /*        LVL */
    {PK_CLOCK, PK_LOOP, PK_ROOM, PK_DECAY,           /* SPACE: TIME FDBK SIZE DEC */
     PK_MIX, PK_MIX, PK_FILTER, PK_BOWTIE,           /*        DLY VERB TONE SPRD */
     PK_PRE, PK_NONE, PK_NONE, PK_NONE},             /*        PRE */
};
static const uint8_t SYN_PK[NPK] = {
    PK_OSC, PK_DETUNE, PK_MIX, PK_NOISE,             /* SYNTH: WAVE DTUN MIX NOIS */
    PK_CUTOFF, PK_RES, PK_ENVAMT, PK_KTRK,           /*        CUT RES ENV KTRK */
    PK_ATTACK, PK_DECAY, PK_SUSTAIN, PK_RELEASE,     /*        ATK DEC SUS REL */
    PK_VOICES, PK_SLEW, PK_DRIVE, PK_KNOB,           /*        VOIC GLID DRV TUNE */
    PK_FADER};                                       /*        LVL */
static const uint8_t POL_PK[NPK] = {
    PK_SRC, PK_START, PK_KNOB, PK_VOICES,            /* POLY: REEL STRT TUNE VOIC */
    PK_ATTACK, PK_DECAY, PK_SUSTAIN, PK_RELEASE,     /*       ATK DEC SUS REL */
    PK_CUTOFF, PK_RES, PK_SLOPE, PK_ENVAMT,          /*       CUT RES TYPE ENV */
    PK_FADER};                                       /*       LVL */
/* the pictograms of device d's knobs on track t (the source: the chosen source's) */
static const uint8_t *dev_pk(uint32_t t, uint32_t d)
{
    if (d != DEV_SRC || tp[t].src == SRC_TAPE)
        return DEV_PK[d];
    return tp[t].src == SRC_SYNTH ? SYN_PK : POL_PK;
}
static const uint8_t CH_PK[NCH] = {PK_SHELF_LO, PK_SHELF_HI, PK_FILTER, PK_PAN};
static const uint8_t MS_PK[NMS] = {PK_KNOB, PK_ATTACK, PK_RELEASE, PK_MIX};   /* the master compressor */
static const uint8_t ME_PK[NME][NPK] = {
    {PK_KNOB, PK_SHAPE, PK_SKEW, PK_FOLD,            /* LFO: RATE SHPE SKEW FOLD */
     PK_CURVE, PK_SMOOTH, PK_VAR, PK_STEPS,          /*      CURV SMTH VAR LEN */
     PK_FADER, PK_FADER, PK_CLOCK, PK_BOWTIE,        /*      AMT OFS PHAS SPRD */
     PK_TOGGLE, PK_TOGGLE, PK_ATTACK, PK_NONE},      /*      SYNC TRIG FADE */
    {PK_ATTACK, PK_DECAY, PK_SUSTAIN, PK_RELEASE,    /* ADSR */
     PK_CURVE, PK_CURVE, PK_CURVE, PK_BOWTIE,        /*      ACRV DCRV RCRV SPRD */
     PK_FADER, PK_TOGGLE, PK_FADER, PK_FADER},       /*      VEL LOOP AMT OFS */
    {PK_STEPS, PK_KNOB, PK_SLEW, PK_SWING,           /* SEQ: LEN RATE SLEW SWNG */
     PK_DIR, PK_TOGGLE, PK_DOTS, PK_STEPAT},         /*      DIR TRIG PROB STRT */
    {PK_SRC, PK_FADER, PK_ATTACK, PK_DECAY,          /* FOLLOW: SRC GAIN RISE FALL */
     PK_STAIRS, PK_FADER, PK_FADER, PK_BOWTIE},      /*         HOLD AMT OFS SPRD */
};
